### ISSUE TITLE
per key rate limit?

### ISSUE THREAD

**Issue by CheweyZ** [nfriedly/express-rate-limit#100]
is it possible or how might I go about having a database table with some preset keys and custom rate limits per each key

preferably without the need of making a new rate limit object per key with its own limits tag

such as may be the ability to add own middleware before rate limit which passes a tag in with the req which rate limit would use rather than just look at option

**Comment by nfriedly** [comment]
Hi,

I believe this is possible by setting up a custom `handler(req, res, next)` function.

First, set  `max` to whatever the lowest value for any user might be (or just `1` if you're sure.)

Then, inside the handler, do your database lookup for the users actual limit. Compare that to `req.rateLimit.current`: 

* If they're below the actual limit, just call `next()`.

* If they're at or above the limit, block them with a 
`res.status(429).end('Too many requests')`.

It's a bit of a hack, but it should work. 

You'll want to disaby the automatic headers and manually set them in the handler function also. (Or just omit the headers).

...or I suppose we could let the `max` option be a function that returns a promise. Would you rather to send a PR for that?

I'm just posting from my phone, but I think that either of those will work. Let me know if something doesn't make sense.
