### ISSUE TITLE
Store with memory fallback

### ISSUE THREAD

**Issue by yonivy** [nfriedly/express-rate-limit#109]
Is there a way to use the redis-store with a fallback to the memory one? This is to prevent redis from being a single point of failure here (in case I don't want to use a cluster).

**Comment by nfriedly** [comment]
I don't know of any way to do that off the top of my head. I'm sure it's possible, but it may require writing your own store.

**Comment by yonivy** [comment]
Fair enough. If I'll get to implement one I'll open a pull request to see if it's in any interest to you.
