### ISSUE TITLE
Add a `CHANGELOG`

### ISSUE THREAD

**Issue by ehmicky** [nfriedly/express-rate-limit#114]
Thanks for this project!

Would it be possible to add a `CHANGELOG` to make it easy to see new changes without going through commits?

The `README` shows major versions changes, but not minor versions.

**Comment by nfriedly** [comment]
Hi @ehmicky, I'm considering it.

**Comment by pqvst** [comment]
Any chance we can get a change log for 4.0.X?

**Comment by nfriedly** [comment]
There were no changes to the code, just tweaks to the typescript typings.

**Comment by ehmicky** [comment]
Thanks @nfriedly and @gamemaker1!
