### ISSUE TITLE
Throw Exception in Handler

### ISSUE THREAD

**Issue by johannesschobel** [nfriedly/express-rate-limit#118]
Dear @nfriedly ,

first of all - thank you for this nice package allowing to throttle down my API - really handy and easy to use.

In my application, build with NestJS, i use a global "ExceptionHandler" to handle all Exceptions thrown in my application and format them accordingly (e.g., based on the JSON:API specification).

Currently, if a user hits the `RateLimit`, a normal text message is sent back (along with the proper HTTP status!). However, i would like to format this message accordingly. As this feature (formatting) is already implemented, i would like to `throw new RateLimitExceededException();` in this case.

However, if i tried to set the `handler` like this:
```ts
{
   // other config params
   handler: ((req, res) => {throw new RateLimitExceededException()});
}
```
this resulted in an error and unhandled promise rejections.. Is this possible to throw an exception? And if so, how?

The basic problem is, that the clients may decide (based on `http headers`) in which format they want to receive the content (`application/vnd.api+json; application/json; text/html; text/xml; ...`) and of course, exceptions must be formatted accordingly..

All the best and thank you very much for your help

**Comment by nfriedly** [comment]
It should work the way you describe it, so there might be a bug there.


I'm out with only a phone, so I can't dig too deeply into that right now, but I do have a possible workaround: Try adding a third param and passing the exception to that instead if throwing.


```js
{ 
// other config params 
handler: (req, res, next) => next(new RateLimitExceededException()),
}
```

**Comment by johannesschobel** [comment]
Hey there,

Wow, thanks a lot for that quick response.. I will try to test that tomorrow and give feedback!

Thanks a lot and have a nice evening

**Comment by johannesschobel** [comment]
Hey @nfriedly ,

thank you very much for your help - your mentioned approach perfectly works! That is awesome :+1: 

In my specific use-case, I had the additional issue, that i need to ensure the proper order of the execution of middlewares. e.g., there is a middleware that detects the proper `Accept` format the user requests - and of course, this middleware needs to be executed **before** the actual `RateLimitMiddleware` that is provided with your package..

But it now works ;) Thank you very much for your help!
