### ISSUE TITLE
Silly question: Does this limit based on IP? Or per endpoint?

### ISSUE THREAD

**Issue by cloesd22** [nfriedly/express-rate-limit#120]
When you apply this to an endpoint, will this rate limit each user individually? (ie; user A sends 100 requests per second and gets rate limited.. is UserB also rate limited during this time, is the whole server rate limited?).

I see that it uses a req.ip, so I believe it's done per user? Is that correct?

Thanks.

**Comment by nfriedly** [comment]
The default is per IP, so UserB would not get limited unless they were on the same IP as UserA.

This is also configurable, so you could use something other than IP if you wanted.
