### ISSUE TITLE
windowMs doesn't change anything

### ISSUE THREAD

**Issue by Andy671** [nfriedly/express-rate-limit#124]
Here is my code.
```
var rateMongoStore = new RateMongoStore({
  uri: dbUri,
  collectionName: 'records'
})

var limiter = RateLimit({
  windowMs: 15 * 60 * 1000,
  max: 1200,
  store: rateMongoStore
})

server.use(limiter)
```
The expirationDate in mongoDB for new ip's is the same. It is just a minute after the first request (default).
Can it be the issue with the last release?

**Comment by nfriedly** [comment]
You need to pass the `expireTimeMs` option to the mongo store:

```js
var rateMongoStore = new RateMongoStore({
  expireTimeMs: 15 * 60 * 1000,
  uri: dbUri,
  collectionName: 'records'
})

var limiter = RateLimit({
  windowMs: 15 * 60 * 1000,
  max: 1200,
  store: rateMongoStore
})

server.use(limiter)
```

Having to pass the same number to both configs isn't ideal, but it would be a breaking change at this point.

**Comment by Andy671** [comment]
Thanks! Works nice!
