### ISSUE TITLE
Is there a way to limit request based on some other arbitary condition ?

### ISSUE THREAD

**Issue by udithv** [nfriedly/express-rate-limit#125]
Is there a way to rate limit based  some arbitrary condition like user id in addition to IP address or without  using IP address as a criteria.

**Comment by nfriedly** [comment]
Yes, take a look at https://github.com/nfriedly/express-rate-limit/issues/123#issuecomment-466792974 for an example

**Comment by udithv** [comment]
Does `keyGenerator` expect a `boolean` value....after reading some it expects some kind of unique string.
