### ISSUE TITLE
Documentation issue relating to multiple rate limiters?

### ISSUE THREAD

**Issue by jordancue** [nfriedly/express-rate-limit#130]
I may be overlooking something obvious, but the README documentation called "Create multiple instances to apply different rules to different routes:" is misleading and doesn't function the way I would expect without further customization (found this out the hard way). 

```
const rateLimit = require("express-rate-limit");

app.enable("trust proxy"); // only if you're behind a reverse proxy (Heroku, Bluemix, AWS ELB, Nginx, etc)

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100
});
app.use("/api/", apiLimiter);

const createAccountLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // start blocking after 5 requests
  message:
    "Too many accounts created from this IP, please try again after an hour"
});
app.post("/create-account", createAccountLimiter, function(req, res) {
  //...
});
```

From reading this example, it would appear to me that the `/api/` routes can be accessed 100 times within a 15 minute window before an error is thrown and that the `/create-account` endpoint can *separately* be accessed 5 times within a 1 hour window before an error is thrown and the rate limiter blocks the route. This is emphasized by the example's error message "Too many accounts created from this IP, please try again after an hour"

What happens in reality is that 5 hits to *either* endpoint in a 15 minute window will cause the createAccountLimit ratelimiter to block access to the `/create-account` endpoint, even if the user had never previously tried to create an account at all. This example needs to also include the documentation regarding setting the storage key based on request endpoint to work as expected.

**Comment by nfriedly** [comment]
I need to dig into this a bit more, because it looks correct to me. Did you run this exact example?

**Comment by jordancue** [comment]
Not this exact example -- I'm using 4-5 different rate limiter instances for various endpoints in our API

**Comment by nfriedly** [comment]
Aah, ok, and it sounds like you are also using an external store? That would cause the behavior you're seeing. 

I think the example works as expected, but it's probably deserves some additional notes for what all needs to change when you switch to using an external store. 

Would you like to send a pull request with those notes?

**Comment by jordancue** [comment]
Aha, yep that would be it! I recently switched over to using an external store.

I wouldn't feel comfortable making an official recommendation for the docs on what the fix/workaround should be though.

**Comment by nfriedly** [comment]
Ok, I'll put something in there
