### ISSUE TITLE
Question about changes made in 3.4.1 (tanium.com resolved value)

### ISSUE THREAD

**Issue by sawyerh** [nfriedly/express-rate-limit#131]
I see that in v3.4.1, dependencies in the `package-lock.json` were updated to point to `artifactory.corp.tanium.com`. Can you provide more context for [this change](https://github.com/nfriedly/express-rate-limit/commit/ac58dc1a58c5f2bd865372dab79d06254c11f10e)?

**Comment by nfriedly** [comment]
Oh, shoot, that was a mistake. There was a security vulnerability in one if the dependencies, and I updated it on my work laptop, forgetting that uses my work npm registry. 

I'm on my phone right now, bit I'll straighten it out once I get back to my computer.
