### ISSUE TITLE
Options default set in passed argument object

### ISSUE THREAD

**Issue by Alirun** [nfriedly/express-rate-limit#132]
I considered following code to be working
```
const RateLimit = require('express-rate-limit')

const options = {
  windowMs: 5 * 1000, // 5 seconds
  max: 1
}

const ordersLimit = RateLimit(options)
const usersLimit = RateLimit(options)
```

But requests to `ordersLimit` middleware were blocked by limit of `usersLimit` middleware and vice versa.

I did expect that options object is not directly used and modified within constructor, but it is.

So option.store was set in first constructor call and used as provided in second call.

If it's expected behaviour, please at least add a note in README. If not, I could make a PR to fix this by creating new object in constructor.

**Comment by nfriedly** [comment]
Aah, that's tricky. I never intended for that behavior, but I have a bit of a concern that changing it now could break some existing code. 

I'll go ahead and change it from `defaults(options, {/*default opts*/})` to `Object.assign({}, {/*default opts*/}, options)` and drop the `defaults` dependency. And then I'll mark it as a major version bump when publishing it.
