### ISSUE TITLE
Can be bypassed with "X-Forwarded-For" header

### ISSUE THREAD

**Issue by Overtorment** [nfriedly/express-rate-limit#134]
Example:

curl  --header "X-Forwarded-For: 127.0.0.6"   -i  "my url"

```
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 99
```
curl  --header "X-Forwarded-For: 127.0.0.6"   -i  "my url"

```
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 98
```

curl  --header "X-Forwarded-For: 127.0.0.7"   -i  "my url"

```
X-Ratelimit-Limit: 100
X-Ratelimit-Remaining: 99
```

whats the solution..?
PS. Behind Heroku, have `app.enable("trust proxy")`

**Comment by nfriedly** [comment]
Try setting `app.set('trust proxy', 1)`, see https://expressjs.com/en/guide/behind-proxies.html for more info.

**Comment by Overtorment** [comment]
solved it, thanks!

**Comment by nfriedly** [comment]
Cool, I might change that in the examples
