### ISSUE TITLE
`store` Option with TypeScript.

### ISSUE THREAD

**Issue by oxala** [nfriedly/express-rate-limit#136]
Readme says that there is a default value for `store` option. https://github.com/nfriedly/express-rate-limit#store

But whoever created *.d.ts file within this repo, required `store` attribute to be passed in. 
https://github.com/nfriedly/express-rate-limit/blob/master/index.d.ts#L8

While DefinitelyTyped interface is being correct.
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-rate-limit/index.d.ts#L95

I'm not sure if I can tell TypeScript to respect `@types` instead of local module types declaration. 

Should `store` be optional in `index.d.ts`, or should be `index.d.ts` removed altogether and types to be maintained within DT?

**Comment by nfriedly** [comment]
`store` should be optional, can you send me a PR with the fix?

**Comment by oxala** [comment]
I was too late. Thnx for the fix.

**Comment by nfriedly** [comment]
Haha, yea, no worries. 

If you want to help out, we could really use some tests that are written in typescript. Or just change the current ones to .ts I suppose. I'll file a ticket for that.
