### ISSUE TITLE
Compilation error TS2309 with latest TypeScript

### ISSUE THREAD

**Issue by juergenzimmermann** [nfriedly/express-rate-limit#140]
Using TypeScript `3.5.0-rc` I get the following error message:

```
node_modules/express-rate-limit/index.d.ts:32:1 - error TS2309: An export assignment cannot be used in a module with other exported elements.

32 export = RateLimit;
```

When I remove the last line in `index.d.ts` and add `export` in front of `declare function RateLimit(` then the issue is gone.

**Comment by nfriedly** [comment]
Ok, want to send me a PR with that change? (I'm on my phone right now.)

I could also use some help with TS testing if you're up for it - #138

**Comment by derSoerrn95** [comment]
#141
