### ISSUE TITLE
TypeScript TS7009 & TS2309 Error

### ISSUE THREAD

**Issue by jecsham** [nfriedly/express-rate-limit#142]
Version:
4.0.2
Running `tsc` command
```
node_modules/express-rate-limit/index.d.ts(32,1): error TS2309: An export assignment cannot be used in a module with other exported elements.
src/index.ts(17,20): error TS7009: 'new' expression, whose target lacks a construct signature, implicitly has an 'any' type.
```

**Comment by nfriedly** [comment]
Please update to 4.0.3, and let me know if it fixed that issue.

**Comment by sliktrik** [comment]
can confirm the issue still exists on 4.0.3

**Comment by jecsham** [comment]
The issue still.

You are not exporting RateLimit function by default so we can import to our project with
`import { RateLimit } from "express-rate-limit";`

and delete the `new` when we want instace cause `RateLimit` is not a class with constructor.
