### ISSUE TITLE
rate limiting by IP question

### ISSUE THREAD

**Issue by foobar8675** [nfriedly/express-rate-limit#148]
I had a question regarding rate limiting by IP. I have a consumer app where users could come from an ISP. I'm assuming many of the ISPs using some kind of NAT thing where multiple clients would appear as the same IP as far as node is concerned.

So, if I add the rate limiting code using `express-rate-limit`, isn't it possible to accidentally rate limit valid requests?

**Comment by nfriedly** [comment]
That is possible, but I've never seen it be an issue in practice. 

You can, for example, allow users to sign in and then use their userid as the key for signed in users, and the IP for anonymous users. That would provide an easy workaround for the CGNAT concern.

**Comment by foobar8675** [comment]
thank you.
