### ISSUE TITLE
Use rate-limiter-flexible package as a base rate limiter

### ISSUE THREAD

**Issue by animir** [nfriedly/express-rate-limit#150]
[rate-limiter-flexible](https://github.com/animir/node-rate-limiter-flexible) is a well tested rate limiter. It provides many features over atomic increments for different store types: Redis, process Memory, Cluster or PM2, Memcached, MongoDB, MySQL, PostgreSQL.

It works with many underlying store client libraries. `rate-limiter-flexible` also provides Black/White features, Insurance Strategy, in-memory Block Strategy and more.

@nfriedly I believe, some features of `rate-limiter-flexible` as a base library would be useful for `express-rate-limit` future improvements too.

**Comment by nfriedly** [comment]
Hi @animir 

That's an interesting idea...

On the one hand, I can see the appeal: joining forces, reducing duplication, synergy, etc.

On the other hand, though, it would be a very significant change that would almost certainly break some things for some end users. 

On the ballance, I don't think benefits would be worth the pain it would likely take to get there. 

That's not to say that there's anything wrong with rate-limiter-flexible - quite the opposite in fact! There's a reason I added your link to the readme, it really is a more appropriate option for a lot of use-cases.

If I was starting out fresh today, it'd be different. But at this point, there are literally thousands of people who depend on this project, and it's already had too much thrashing recently with typescript typings (which is apparently a lot harder to get right than it sounds), and I just don't want to put those users through any more unnecessary trouble.

Beyond that, I also have personal reasons for not wanting to make any major changes to this lib, mostly just not having the time available to do any significant development.

So, thank you for the suggestion, I do appreciate it, but I'm not going to go down that route at this point.
