### ISSUE TITLE
Using multiple instance of rate limiters on single route point

### ISSUE THREAD

**Issue by madavraman** [nfriedly/express-rate-limit#151]
Hi,

I would want to limit a route API something like, 3/min and max 3/hour. So I would be adding two rate limiters something like this.

```js
var router = express.Router();

const apiLimiter = rateLimit({
    windowMs: 3 * 60 * 1000, // 30 secs window
    max: 3,
    message:  "Too many wrong"
});

const apiLimiter2 = rateLimit({
    windowMs: 60 * 60 * 1000, // 2 mins secs window
    max: 3,
    message:  "Blocked for 1 hour"
});

router.route('/api/abcdroute')
    .post(apiLimiter)
    .post(apiLimiter2)
```

I see that the second rate limiter is not working consistently. Can someone please let me know what I'm doing is right? Or is there some alternative.

**Comment by nfriedly** [comment]
Can you clarify what behavior you're seeing?

The comments on `windowMs` are incorrect, but I don't think that's the main issue here.

**Comment by madavraman** [comment]
Sorry about the comments in windowsMs, this is not what was intended.

Consider following scenarios to keep the issue simple.
Scenario 1: I want to allow max 3 request in 20secs and maximum 3 requests in 1 minute.
Scenario 2: I want to allow max 3 request in 20secs and maximum 3 requests in 2 minute.

Scenario 1:
------------
const apiLimiter = rateLimit({
    windowMs: 20 * 1000,
    max: 3,
    message:
      "Too many requests"
});
const apiLimiter2 = rateLimit({
  windowMs: 60 * 1000,
  max: 4,
  message:
    "Too many requests 2"
});

router.route('/api/abcdroute')
    .post(apiLimiter)
    .post(apiLimiter2)

Limit observed behavior is 50secs limit instead of 60 mins

Scenario 2:
------------
const apiLimiter = rateLimit({
    windowMs: 20 * 1000,
    max: 3,
    message:
      "Too many requests"
});
const apiLimiter2 = rateLimit({
  windowMs: 2 * 60 * 1000,
  max: 3,
  message:
    "Too many requests 2"
});

Limit observed behavior is 1:45 mins limit instead of 2 mins

**Comment by nfriedly** [comment]
Ok, I think the misunderstanding is with how the window works. The reset happens every 2 minutes (or whatever), but it's just a single timer that loops - so any specific user may see a reset happen before 2 minutes because they started on the middle of a loop. This is a memory/performance optimization. 

In my experience, this is sufficient to prevent abuse.

However, to change this behavior, you can use an external store, all of which have precise, per-user timers, or try a different library (there are a few linked from the readme).

**Comment by madavraman** [comment]
@nfriedly Thanks for the clarification.
I basically want to have 3 attempts for 30 secs and max 20 attempts in a day.
I'm fine if the 2nd limit is almost near to a day, not considerably less than a day. In that case will increase second limit to be few hours more than a day.

**Comment by nfriedly** [comment]
I think you should be fine. 

It does include headers on the response by default that let end users know how many requests they have left and when it will reset, but they might be a little confusing in your case.  I believe the second one will overwrite the headers for the first one if they both run, but if the user gets blocked by the first handler, then the second one won't run and therefore won't overwrite the first one's headers.  

So, for example, if a user makes 4 requests in a 30-second period, the 3rd request's headers will indicate 17 requests remaining and a reset time in the next 24 hours, but the 4th request will be blocked with headers indicating 0 requests remaining and a reset time within the next 30 seconds.

You might want to just disable the default headers (`{headers: false}`) to avoid that confusion.

**Comment by Martii** [comment]
Been thinking about doing this particular idea of implementation on our project as well for a few weeks. Haven't decided yet... so I'm all :eyes* here. :smile_cat:

**Comment by Martii** [comment]
@madavraman 

Wouldn't:

``` js
router.route('/api/abcdroute')
.post(apiLimiter)
.post(apiLimiter2)
```

be better expressed as:

``` js
router.route('/api/abcdroute')
.post(apiLimiter, apiLimiter2, someValidatedAction)
```

or did I miss the boat? The latter is how we've been doing it even with another package that limits requests before we moved to this one.

**Comment by madavraman** [comment]
@Martii 
router.route('/api/abcdroute')
.post(apiLimiter)
.post(apiLimiter2)

I think both are same but different ways of expressing, even the above works for me except as @nfriedly  confirmed due to timer optimisation time at which it is reset is not exact.

**Comment by madavraman** [comment]
@nfriedly Looks like while using multiple rate limiters, if one user reaches the limit others users are also getting blocked, do you know why this might be happening.

I'm using something like this, if one user tries wrong password 20 times, it is blocking all other users.

const loginRequestDailyLimiter = rateLimit({
    windowMs: 24 * 60 * 60 * 1000, // 24 hours
    max: 20,
    message:
      "Too many tries with wrong password for the today"
});

const loginRequestLimiter = rateLimit({
    windowMs: 30 * 1000, // 30 secs window
    max: 3,
    message:
      "Too many tries wrong password"
});

router.route('/login')
    .post(loginRequestDailyLimiter)
    .post(loginRequestLimiter)

**Comment by madavraman** [comment]
issue looks similar to #92

**Comment by madavraman** [comment]
If I do not set keyGenerator it will pick the default one right?
console.log(req.ip) is able to print the ip address. I'm using AWS for hosting the server. I see even on the AWS server I'm able to print req.ip

**Comment by nfriedly** [comment]
@madavraman You might need to call `app.use('trust proxy', 1);` or something along those lines.

AWS configurations often send traffic through a reverse proxy, and then, from the server's perspective, all requests are coming from the same IP (the proxies). However, the proxy will usually set a header with the original IP, and that config option lets express know that it's OK to trust that header. 

See https://expressjs.com/en/guide/behind-proxies.html for more info

**Comment by madavraman** [comment]
@nfriedly Thanks for the guidance, the issue was with the AWS.
