### ISSUE TITLE
Provide an alternate to npm for JS compiled from TS

### ISSUE THREAD

**Issue by nfriedly** [nfriedly/express-rate-limit#153]
@Martii brought up a good point in the context of transitioning to Typescript (#138 & #152):

> >  ... With the current setup in this branch, installing directly from github won't work
>
> This could be a potential 👎

https://github.com/nfriedly/express-rate-limit/pull/152#issuecomment-509433428

I agree with this sentiment. I think github releases is probably the correct place to store the compiled code on github, but I'm not sure if npm can install from a github release, so we may need to also stick it into git in order to meet that need.

**Comment by googol** [comment]
Npm can install from a tarball provided from a https url, so if travis is configured to do a second deploy (with a script of `npm run build && npm pack`) there, it would solve this issue.
