### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Roki100** [nfriedly/express-rate-limit#156]
is this possible to like "whitelist" ip/req.param from being rate-limited without making next endpoint?
or use other rate-limit for ip/req.param?

**Comment by nfriedly** [comment]
Yes, you can set `skip` to a function like so:

```js
const limiter = rateLimit({
  skip: (req, res) => {
    if (req.ip === '1.2.3.4') {
       return true;
    } else {
      return false;
    } 
});
```

That will whitelist the IP 1.2.3.4.

**Comment by developdeez** [comment]
I've noticed adding skip and returning true. It stops my call from continuing. How can I debug this?
