### ISSUE TITLE
can you add license file

### ISSUE THREAD

**Issue by toobug007** [nfriedly/express-rate-limit#158]
This project is good and easy to use. Can you help to add the license file with MIT protocol, so that every one can use it more confidently.

**Comment by nfriedly** [comment]
Done!

In my opinion, the license declaration in the package.json is sufficient:

https://github.com/nfriedly/express-rate-limit/blob/d14b834f9d9a961f60c549d26f126604e6ec58b6/package.json#L11

But, if the standalone license file makes your life easier, then it's fine with me :)
