### ISSUE TITLE
Timeleft

### ISSUE THREAD

**Issue by tabam1** [nfriedly/express-rate-limit#162]
Can I check how much time I have left to complete my request?
I want like this e.g: message: "You must wait 0.5 seconds to the next request"

**Comment by nfriedly** [comment]
Yes, with one pre-condition: the store must provide that time. The built-in memory store does, but I'm not sure about the other stores available. When the store supports it, `req.rateLimit.resetTime` will be set to a timestamp (in milliseconds).  

Then you need to pass a `handler` function in the config to customize the outgoing message:

```js
app.use(rateLimit({
    // ...
    handler: function(req, res) {
      const milliseconds = req.rateLimit.resetTime - Date.now();
      const seconds = Math.round(milliseconds/1000);
      res.status(429).send(`You must wait ${seconds} seconds to the next request`);
   }
}));
```

I didn't test that, but it should be pretty close to what you want.

**Comment by tabam1** [comment]
Many thanks that's exactly what I meant.
