### ISSUE TITLE
Which IP does it target (e.g. in express: req.ip or req.headers["x-forwarded-for"])

### ISSUE THREAD

**Issue by arnoubrecht** [nfriedly/express-rate-limit#165]
Hey all, 

I got a question concerning the express-rate-limit, which IP it gets. Since my setup consists of a front-end static web app, calling my API (serverless firebase cloud function). I use express-rate-limit, to get a extra layer of security against DDoS attacks. I also use express, so I tried to log my IP with (req.ip), this gives me the IP of my front-end web app, being the same for every user. However, I also found the req.headers["x-forwarded-for"], being the IP of the user of the front-end app. Having this said, my question is which IP express-rate-limit targets to set a limit. The one of my front-end web app or the one of the actual user of the front-end web app?

Kind regards,
Brecht

**Comment by nfriedly** [comment]
This checks `req.ip` and express automatically sets that to the the end-user's IP if you configure it to.  Set:

`app.set('trust proxy', 1);`

See https://expressjs.com/en/guide/behind-proxies.html for more info.
