### ISSUE TITLE
Get message when limit exceeded max

### ISSUE THREAD

**Issue by agustinl** [nfriedly/express-rate-limit#167]
Hi all,
I don't know if I am confused, or dont understand something in docs.

When I declare a message,

```
const createAccountLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // start blocking after 5 requests
  message:
    "Too many accounts created from this IP, please try again after an hour"
});
```

how can I capture that if limits exceeded the max?

I want to send it to the front, to show it in the page.

Thanks 😀

**Comment by nfriedly** [comment]
Hi @agustinl,

I'm not entirely sure I understand the question are you wanting to capture it in client-side code or in server-side code? If client-side, you might want to do something like this:

If you're wanting to capture it in client-side code, then you may want to return a JSON response like so:

```
const createAccountLimiter = rateLimit({
  windowMs: 60 * 60 * 1000, // 1 hour window
  max: 5, // start blocking after 5 requests
  message: {
    error: "Too many accounts created from this IP, please try again after an hour"
  }
});
```

Does that help?

**Comment by agustinl** [comment]
Hi @nfriedly , thanks for you response,
Yes, I want to capture in the client side, 
I have a app router like this:

```
router.post('/', createAccountLimiter, async function (req, res) {

});
```

But where should JSON return?
How do I check that the limit was exceeded and that I should return the message?

I hope to be clear, thanks for the help!

**Comment by nfriedly** [comment]
Sorry, I've been slow to respond.

If you change

```js
  message:
    "Too many accounts created from this IP, please try again after an hour"
```
to
```js
  message: {
    error: "Too many accounts created from this IP, please try again after an hour"
  }
```

That makes the server return JSON instead of just plain text in the event that the user is blocked. 

On the client side, it really depends on yow you're making the request. If you're using `fetch()` then it might look something like this:

```js
const response = await fetch('/');
if (response.status === 429) {
    console.log('blocked by the rate limiter');
} 
const myJson = await response.json(); // this assumes the server always returns JSON
console.log(JSON.stringify(myJson));
```

**Comment by agustinl** [comment]
Thanks Nathan, is very clear now!

Nice weekend.
