### ISSUE TITLE
record hits per IP per route

### ISSUE THREAD

**Issue by jazoom** [nfriedly/express-rate-limit#17]
Perhaps the next feature could be allowing a different record for each route like express-brute?

This means that I can allow a particular IP to access `/routeA` 50 times in an hour and `/routeB` 30 times per minute.

**Comment by nfriedly** [comment]
This is possible currently by creating two instances:

```js
var rateLimit = require('express-rate-limit');

var limiterA = rateLimit({
  windowMs: 60*60*1000, // 1 hour
  max: 50
  delayAfter: 0, // disable delaying
});
app.use('/routeA', limiterA);

var limiterB = rateLimit({
  windowMs: 60*1000, // 1 minute
  max: 30
  delayAfter: 0, // disable delaying
})
app.use('/routeB', limiterB);
```
Will that meet your needs?

**Comment by jazoom** [comment]
I guess it will. I did think of doing that but I assumed it was a singleton since there was no `new` keyword.

Thanks for the info!

**Comment by nfriedly** [comment]
Yea, I should probably change that...

**Comment by nfriedly** [comment]
There we go, I updated the readme to be a bit more clear (it's actually works either way, but using `new` should make things a bit more clear) and I added a section for creating different instances for different routes. Should be live as v2.1.3 shortly, although there weren't any code changes.

**Comment by jazoom** [comment]
Great stuff! Thanks.
