### ISSUE TITLE
Skip seems to prevent the call from completing

### ISSUE THREAD

**Issue by developdeez** [nfriedly/express-rate-limit#170]
Trying to skip the rate limit for certain calls but after adding skip. It seems returnign true causes it to not execute.

**Comment by nfriedly** [comment]
That sounds like a bug, I don't know if I'll have a chance today, but I'll try and look and do it soon. In the meanwhile I suppose you could set max to a function that returns `Infinity` for request you want to skip

**Comment by developdeez** [comment]
Im using graphql (1 endpoint). Otherwise, yes that would be the approach.
Thanks for responding.

**Comment by nfriedly** [comment]
I took a quick look, and I'm not seeing anything that would cause that behavior. The [code behind skip](https://github.com/nfriedly/express-rate-limit/blob/master/lib/express-rate-limit.js#L52) is pretty simple, and there is a test case where the skip function returns true:

https://github.com/nfriedly/express-rate-limit/blob/757fb450241748ba970315c81df203a9bbd394ba/test/express-rate-limit-test.js#L496-L512

(`goodRequest()` [validates the response](https://github.com/nfriedly/express-rate-limit/blob/757fb450241748ba970315c81df203a9bbd394ba/test/express-rate-limit-test.js#L144))

Can you create a new test case that reproduces the issue you're seeing?

**Comment by developdeez** [comment]
Weird. I'll try to make a reproduction. Sounds like I might be missing
something

**Comment by developdeez** [comment]
Tried again, Using this
```
const limiter = RateLimit({
  store: new RedisStore({
    client: RedisClient
  }),
  max: 7500,
  windowMs: 30 * 1000,
  skip: req => {
    return false;
  }
});
```

When I return false everything works fine. When I return true it doesnt have the same request. I saw the ratelimit object is removed from the req when it continues. Does ti remove anything else when true is returned?

**Comment by developdeez** [comment]
Is there another way to do this?

**Comment by developdeez** [comment]
I just noticed it chages the req. At one point I could get my values destructing body. But with this package the body is now within a larger object. Hence why it breaks the calls

**Comment by developdeez** [comment]
Opted for using a call separate of the main since this didn't work for me. new ticket made
