### ISSUE TITLE
Return a problem+json by default in case of 429

### ISSUE THREAD

**Issue by ioggstream** [nfriedly/express-rate-limit#171]
## I expect

The default 429 message to be a problem+json RFC 7807 message
with an error payload.

## instead

I 
See       message: "Too many requests, please try again later.",

**Comment by nfriedly** [comment]
This is supported by setting the `message` option to an object, or by setting `handler` to a function to send responses that vary based on the situation.

This library is used for both APIs and human-facing services, so it wouldn't make sense to *only* support returning JSON, and I think RFC 7807 support might be beyond it's scope. 

An earlier version used `Accept` headers to vary the response, but it proved to cause more confusion than benefit.
