### ISSUE TITLE
Erratic blocking behavior

### ISSUE THREAD

**Issue by GermanAntonio2** [nfriedly/express-rate-limit#172]
Hello.

I am experiencing an erratic behavior with the rate limiter and I'm quite suspicious there's something I'm not seeing.

I'm using the middleware only at my sign-in API.

```js
const apiLimiter = require('../services/api-limiter');
router.post('/api/users/sign-in', apiLimiter, async (req, res, next) => {
// sign-in logic
// send 401 on failed attempt
// send 204 on successful
});
```

My API limiter service is as follows:
```js
const RateLimit = require('express-rate-limit');
const config = require('../configs/api-limiter');
const apiLimiter = RateLimit(config);
module.exports = apiLimiter;
```

And it is configured like this (using RedisStore):
```js
const RedisStore = require('rate-limit-redis');
const second = 1000;
const minute = 60 * second;
/* Generates the key to identify the requests' origin */
function keyGenerator(req) {
    return '${req.body.email || ''}+${req.ip}'
}
/* Handler for when the rate limit has been exceeded */
function handler(req, res) {
    res.status(426).send('Too many sign-in attempts. Please try again later...');
}
const apiLimiter = {
    windowMs: 60 * minute,
    max: 3,
    store: new RedisStore({
        redisURL: process.env.SESSION_URI
    }),
    keyGenerator,
    handler
};
module.exports = apiLimiter;
```

This is a NodeJS application that runs inside of a Docker container which is hosted at an AWS EC2 instance (I mention this in case there's some network implications, I'm quite a rookie when it comes to networking).

Though the handler functions does get called "eventually", it is usually not after 3 attempts, sometimes after 10, sometimes after 5, there really is no pattern. When the limit is reached, the 426 is indeed returned (I am using 426 as an arbitrary number just for the sake of debugging). However, if I keep attempting to sign-in with wrong passwords, I sometimes get my own 401, and other times the expected 426. Then eventually and randomly a correct sign-in attempt passes through (after a few minutes, not the 60 minutes as seen in my config).

![server-log](https://user-images.githubusercontent.com/58605888/74446065-200b8000-4e56-11ea-8153-250a828610f4.png)

What confuses me is that it "sometimes work" and "sometimes doesn't work". I've read through your whole library's code (it is quite straightforward), so that led me to think there must be something I am not seeing.

I've also read through all of your documentation and issues and feel like reporting this since nobody else faced the same problem.

Help would be greatly appreciated. Thanks in advance!

**Comment by nfriedly** [comment]
hi @GermanAntonio2 

A few things come to mine reading this:

1) The time window must be configured on the store itself, like so:
 ```js
const apiLimiter = {
    windowMs: 60 * minute, // miliseconds
    max: 3,
    store: new RedisStore({
        redisURL: process.env.SESSION_URI,
        expiry: 60 * 60 // seconds
    }),
    // ...
};
```
(This is a bit of a wart in the API and something I'd like to improve eventually so that you only have to specify it once.)

2) if your keyGenerator is actually using single quotes (') rather than backticks (`) around the template string, then it's just returning that string verbatim without filling in the details for each visitor.

To clarify, it should look like this:

```js
function keyGenerator(req) {
    return `${req.body.email || ''}+${req.ip}`
}
```

not like this:

```js
function keyGenerator(req) {
    return '${req.body.email || ''}+${req.ip}'
}
```
(Although I understand if that was just a transcription issue. I reformatted your code slightly to get syntax highlighting, which might also prevent that issue in the future - see the syntax highlighting section on https://guides.github.com/features/mastering-markdown/)

I believe the first point explains at least part of the confusion you're seeing.

A couple of other questions: 
* Do you have a single node.js process, or multiple processes (e.g. with the [cluster](https://nodejs.org/api/cluster.html) module)?
* Is there any kind of reverse proxy or load balancer between your server and the internet?

**Comment by GermanAntonio2** [comment]
@nfriedly Thanks for your dedicated response. 

You were right about the template string in my keyGenerator method, it was a transcription thing, I am actually using backticks. I apologize for not being able to format the code in my question appropriately.

I will try setting the options in the RedisStore config object. If the default window is a 1 minute lapse, it would sort of make sense with the strange behavior I saw.

As for your questions at the end: 
- _Do you have a single node.js process, or multiple processes?_ 
I use PM2 and it runs a single process in cluster mode.
- _Is there any kind of reverse proxy or load balancer between node.js and the internet?_
Yes, I am using AWS CloudFront as a reverse proxy.

**Comment by GermanAntonio2** [comment]
@nfriedly no luck.

I added the `expiry` property into the RedisStore configuration object with the same value (1 hour) in seconds, while keeping the property `windowMs` at the outter object with 1 hour in miliseconds. The `max` property is set to 5.

Below is a screenshot from the browser's devtools network tab:

![sign-in-logs](https://user-images.githubusercontent.com/58605888/74965527-27053600-53f4-11ea-99ae-b5ea282946b8.png)

All of these request where consecutive (I just kept pressing the sign-in button repeatedly with a wrong password) so all of them happened in between a 20 seconds window. As you can see, there are several 401s before the first 429 (more than 5); and then some random 401/429 responses with no apparent pattern.

I will keep watch over this issue as I cannot deploy the feature to my clients in this current state.

Thanks in advance for your support!

**Comment by GermanAntonio2** [comment]
@nfriedly I tried again with a different `keyGenerator` method, this time using only `req.body.email` as the key, and it worked perfectly as expected.

I'm guessing this issue is caused by my reverse proxy sending different IPs to the server on each request. Is there any workaround for this?

Thanks in advance!

**Comment by GermanAntonio2** [comment]
The problem was fixed completely by using 
`app.set('trust proxy', 1)`
in my `server/index.js` file.

I will now close the issue.

Thanks a lot for your support!

**Comment by nfriedly** [comment]
Awesome, glad to hear it's working for you now!
