### ISSUE TITLE
Exclude rate limit for certain IP's

### ISSUE THREAD

**Issue by iamshouvikmitra** [nfriedly/express-rate-limit#173]
Is there a way to completely exclude certain IP's (local IP's). There seems to be a certain problem when I am querying the API from same machine in which the server is running. All of them get's blocked. 

Explaination:
I am using rate-limit in an application which is run on an EC2 machine which is configured to serve at http://abc.examplehost.com. On the same machine I have another service running which when make a request to http://abc.examplehost.com fails with "Max tries ..." while if I reference http://localhost/ it works as expected. When services from other machines or client website or POSTMAN makes a call, it again works as expected. I can't find a reason why this is happening. 
I have already tried using `app.set('trust proxy', 1)`

**Comment by johnnysprinkles** [comment]
Can't you just provide a `skip` function? That has access to the request so it can look at the IP.

**Comment by nfriedly** [comment]
Hi @iamshouvikmitra 

As @johnnysprinkles mentioned, providing a skip function in in your config may be all that you need:

```js
// flatten the object returned from os.networkInterfaces () to an array of IPs
// https://nodejs.org/api/os.html#os_os_networkinterfaces
const ips = Object.values(require('os').networkInterfaces())
  .map(addrs => addrs.map(addr => addr.address))
  .flat();

const limiter = rateLimit({
  skip: (req, res) => {
    // skip ratelimiting for requests from any IP in the list
    // https://github.com/nfriedly/express-rate-limit#skip
    return ips.includes(req.ip);
  },
  // other config 
});
```

I didn't test that, but it should at least give you the right idea.
