### ISSUE TITLE
Limiter freezes calls

### ISSUE THREAD

**Issue by developdeez** [nfriedly/express-rate-limit#175]
I've tried to isolate the call. My goal is to rateLimit typing notifcation. So when the user types it shows typing for a few seconds then goes away.
For some reason this tool makes it so the call gets stuck.
It's like it holding on to the call. In the Network tab each call just hangs saying "(pending)"
```
const typingLimiter = RateLimit({
  store: new RedisStore({
    client: RedisClient
  }),
  max: 12,
  windowMs: 10 * 1000
});
app.post("/typing", typingLimiter, async (req, res) => {
  if (req.body.token) {
    const { chatID, isTyping, token } = req.body;
    await setTyping({ chatID, isTyping, token });
  }
  res.status(200);
});
```

**Comment by nfriedly** [comment]
What version are you on? `npm ls express-rate-limit` should report it.
