### ISSUE TITLE
Rate Limit and Load Balancer

### ISSUE THREAD

**Issue by rajkumarpb** [nfriedly/express-rate-limit#176]
@nfriedly  I applied rateLimit plugin for my api-gateway. It is behind a load balancer. Since all requests will be coming from Load balancer, rateLimit plugin is blocking my IP. But the real purpose it to block client ip and not load balancer ip. How can we do this? I can see you are using req.ip. Instead of that if you are using request-ip plugin which will fetch the client ip it should work. Can you check this?

**Comment by nfriedly** [comment]
I think all you need is this:

```js
// Enable if you're behind a reverse proxy (Heroku, Bluemix, AWS ELB, Nginx, etc)
// see https://expressjs.com/en/guide/behind-proxies.html
app.set('trust proxy', 1);
```

That causes express to automatically parse headers set by most load balancers and update `req.ip` with the end user's IP address.

If that doesn't work for you, you can add your own middleware that runs before unblocker and overwrites `req.ip` with the appropriate value.

**Comment by nfriedly** [comment]
Also, FWIW, I think Amazon's API Gateway has some built-in rate-limiting, so you may find that you don't need this library at all. There's some info here: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-request-throttling.html

**Comment by rajkumarpb** [comment]
@nfriedly  When I try to add trust proxy in nestjs, I'm getting error. Any idea how to fix this?

```
Router.use() requires a middleware function but got a string +5ms
TypeError: Router.use() requires a middleware function but got a string
```

**Comment by nfriedly** [comment]
Hum, ok, I'm [asking the Nest folks for guidance here](https://github.com/nestjs/nest/issues/4249) because I've not sure what the right answer is. 

One possible workaround may be to make your own middleware that uses the same [proxy-addr](https://www.npmjs.com/package/proxy-addr) library that Express does.

**Comment by nfriedly** [comment]
Ok, we've just updated the [Nest docs](https://docs.nestjs.com/techniques/security#rate-limiting) to explain how to do it. 

> When there is a load balancer or reverse proxy between the server and the internet, Express may need to be configured to trust the headers set by the proxy in order to get the correct IP for the end user. To do so, first use the NestExpressApplication platform interface when creating your app instance, then enable the trust proxy setting:
>
> 
> ```ts
> const app = await NestFactory.create<NestExpressApplication>(AppModule);
> // see https://expressjs.com/en/guide/behind-proxies.html
> app.set('trust proxy', 1);
> ```

Can you try that out and confirm that it works?

**Comment by rajkumarpb** [comment]
Let me try it out and update the status!

**Comment by chiragpurohit71085** [comment]
I have used Application Load Balancer and used  nginx as reverse proxy.  I was having same issue and following worked as expected. Now I am getting user's ip address and express-rate-limit is working as expected.
app.set('trust proxy', ture);

**Comment by nfriedly** [comment]
@chiragpurohit71085  That sounds like you have two proxies between your server and the internet, so `app.set('trust proxy', 2);` might be better. You basically want the lowest number that works. `true` means unlimited, but that means that an end-user can set their own `X-Forwarded-For` header with a random IP and essentially get unlimited requests. (You can also define trusted IPs or subnets - see http://expressjs.com/en/guide/behind-proxies.html)

**Comment by chiragpurohit71085** [comment]
Hi

thanks for suggestions. I will do necessary corrections.
