### ISSUE TITLE
Doesn't add in the req.ratelimit if use app.use(limiter) before app.use(cors)

### ISSUE THREAD

**Issue by DimaDevel** [nfriedly/express-rate-limit#178]
Doesn't add in the req.ratelimit if use app.use(limiter) before app.use(cors)
Need to add this mention in the docs.

**Comment by nfriedly** [comment]
That sounds like a bug, preferably it can be fixed rather than documented. What `cors` library are you using?

**Comment by DimaDevel** [comment]
"cors": "^2.8.5"

**Comment by nfriedly** [comment]
It seems to work for me:

```js
const express = require("express");
const rateLimit = require("express-rate-limit");
const cors = require("cors");

const app = express();
app.use(rateLimit({}));
app.use(cors());

app.get("/", (req, res) => res.send(req.rateLimit));

app.listen(3456);
```

That gets me a JSON response with all of the details from the `req.rateLimit` object. You have the 'L' in 'rateLimit' lowercased in the issue title, perhaps that's the problem? Otherwise I'd need to see you code or, ideally, a new test case.
