### ISSUE TITLE
Weird line

### ISSUE THREAD

**Issue by cellcrowd** [nfriedly/express-rate-limit#179]
If this is intended, could you elaborate on what this line is doing as deleting a key on a Date object doesn't make sense to me?

https://github.com/nfriedly/express-rate-limit/blob/92f4f48b0af2024b9b2cd7fe338a5cb279916501/lib/memory-store.js#L38

**Comment by nfriedly** [comment]
Aah, that should have been deleted a while ago. It used to store a separate date object for each user, but it later got switched to a single global date object. I'm on my phone right now, but if you want to send a PR to delete that line, go ahead.
