### ISSUE TITLE
Multiple rateLimiter doesn't work

### ISSUE THREAD

**Issue by vickyrathee** [nfriedly/express-rate-limit#184]
I was trying to use 2 rate limiter in my app, but the 2nd one doesn't work for some reason. 

One is for using the apiKey
Another is for free customers using the req.ip (no api key sent on header)

The customer having apiKey in header/query are allowed to make 10 request per minute or more as per their plan. But the additional ipRateLimiter should add another rate limitation to requests without apikey with `max: 20` in 24 hour window. 

here is my code :

**app.js**

```
if (process.env.NODE_ENV !== 'dev') {
  const {apiKeyRateLimiter, ipRateLimiter} = require('./services/rateLimit');
  app.use(apiKeyRateLimiter);
  app.use(ipRateLimiter);
}
```

**rateLimit.js**
```
const apiKeyRateLimiter = new RateLimit({
    store: new RedisStore({
        expiry: 60, // apiKey rate limit expiry is one minute
        prefix: "rlkey:",
        resetExpiryOnChange: false,
        redisURL: process.env.REDIS_URL,
    }),
    windowMs: 60,
    max: async (req) => {
        const key = req.headers['x-agenty-apikey'] || req.query.apikey;        
        if(!key){ 
            return 10;  // Set to 10 if no api key
        }
        const account = await getAccountByApiKey(key);       
        if(!account){
            return 10;            
        }
        if(account.plan.toUpperCase() === 'BASIC'){
            return 30;
        }
        else if(account.plan.toUpperCase() === 'PROFESSIONAL'){
            return 60;
        }
        else{
            return 10;
        }
    },
    message : {
        status: 429,
        error: 'Too many requests, please try again later'
    },
    delayMs: 0,   
    keyGenerator: (req) => {
        const key = req.headers['x-agenty-apikey'] || req.query.apikey || req.ip;       
        return key;
    },
});

const ipRateLimiter = new RateLimit({
    store: new RedisStore({
        expiry: 24 * 60 * 60 * 1000, // ip rate limit expiry is 24 hours
        prefix: "rlip:",
        resetExpiryOnChange: false,
        redisURL: process.env.REDIS_URL,
    }),
    windowMs: 24 * 60 * 60 * 1000,
    max: 20 ,
    message : {
        status: 429,
        error: 'Too many requests, the free plan is allowed to make 10 request per minute or 20 per day, whichever comes first!'
    },
    skip : (req) => {
        const key = req.headers['x-agenty-apikey'] || req.query.apikey; 
        if(key){
            return true;
        }else{ 
          return false;        
       }
    delayMs: 0,
});

module.exports =  {apiKeyRateLimiter, ipRateLimiter};
```

The `ipRateLimiter` doesn't work and in my test, I am able to make 10 request every minute while it should throw error after max 20 in 24 hours.

**Comment by nfriedly** [comment]
Hum, I don't see anything obviously wrong with the code... does the 20 request limit work as expected if you comment out the apiKeyRateLimiter?

**Comment by vickyrathee** [comment]
I just tested and found you are correct, the ipRateLimiter was not working when I comment apiKeyRateLimiter because in my actual code the skip function is `async` and await execute only when the key is not null, so it doesn't seems to work.. 

skip : async (req) => {
        const key = req.headers['x-agenty-apikey'] || req.query.apikey; 
        if(key){
            const account = await getAccountByApiKey(key);       
            if(!account){
               return false;          
            }else{
                return true;
            }
        }else{
            return false;
        }   
    },

Not sure why

**Comment by nfriedly** [comment]
oh, shoot, I didn't even notice the `async` on the skip function. Right now it does not work with asynchronous skip functions, skip has to be synchronous. But I don't think there's any reason why it couldn't work, so if you want to send a pull request to update it to work with asynchronous functions that would be fine with me. Take a look at how max is handled for an example.

**Comment by nfriedly** [comment]
v5.2 was just released, which includes support for async skip functions
