### ISSUE TITLE
Conditional/Flag based rate limit

### ISSUE THREAD

**Issue by kvikram1988** [nfriedly/express-rate-limit#187]
Hi,

Can we initiate the rate limit conditionally?
`const limitOnWriteAPI = rateLimit({
    windowMs:  60 * 1000,
    max: 100
});`

Eg: `app.post('/createUser/', limitOnWriteAPI, createUser);`

Based on a flag, limitOnWriteAPI has to be called. If the flag is false, then the rate limiting shouldn't be called.

Let me know if this possible, thanks in advance.

**Comment by nfriedly** [comment]
Try using the `skip` function - https://github.com/nfriedly/express-rate-limit#skip - if the flag is false, have your skip function return true, then rate-limiting won't be applied to that request.
