### ISSUE TITLE
Set handler response type to 'txt'

### ISSUE THREAD

**Issue by DadiBit** [nfriedly/express-rate-limit#189]
The handler default should look like the one of express.js, like this:
```
handler: function (req, res /*, next*/) {
    res.status(options.statusCode).type('txt').send(options.message);
}
```

**Comment by nfriedly** [comment]
Yea, the initial release tried to negotiate content types and return the right thing with the right header, but it was too complex and no one really like it. So I switched to express's simpler res.send() which sends objects as JSON and everything else as HTML, and that seems to work pretty well.

Some users do put HTML and/or JSON objects in the message, so forcing the type to text won't work for everyone, but you're of course welcome to override the handler with your own method that does set the type to text.

**Comment by DadiBit** [comment]
What about an option like `{type: 'json'}` and then use `.type(this.type)`

**Comment by nfriedly** [comment]
Yea, I suppose, but I feel like express's default behavior is good enough for most situations (single-line text responses look about the same regardless of the content-type header), and you always have the option of a custom handler function if you care more about the response.

So I just don't think it's worth the overhead of one more option in a library that I feel like has too many options already.

This was never intended to be the best rate-limiting library out there, just a simple lightweight one that could handle some common scenarios.
