### ISSUE TITLE
windowMs not working when set to 3600000

### ISSUE THREAD

**Issue by aksharj** [nfriedly/express-rate-limit#198]
Hi All,

my apologies in case this is something very trivial.

I have the below code, currently testing on my local machine. I a trying to set the `windowMs` to `3600000` but somehow it gets applied to only one minute.

below is the relevant part of the code.

```
  let client;
  if(process.env.NODE_ENV == 'development') {
    client = redis.createClient();
  } else {
    client = redis.createClient('redis://redis:6379/13');
  }
  const limiter = new RateLimit({
    store: new RedisStore({
      client: client
    }),
    max: 20,
    delayMs: 0,
    windowMs: 3600000
  });
  app.use(limiter);
```

I would expect the user to see the rate limit error for an hour before the user can again access the API. if its of any help, I start my local server by using the command `pm2 start server`

Any help on how to fix this will be really helpful, Thanks.

**Comment by nfriedly** [comment]
Hey, I'm sorry, this is a frustration with the current API. The RedisStore needs to also be told the time limit, but in seconds and via the `expiry` field like so:

```js
  let client;
  if(process.env.NODE_ENV == 'development') {
    client = redis.createClient();
  } else {
    client = redis.createClient('redis://redis:6379/13');
  }
  const limiter = new RateLimit({
    store: new RedisStore({
      client: client,
      expiry: 360 // seconds
    }),
    max: 20,
    delayMs: 0,
    windowMs: 3600000 // miliseconds
  });
  app.use(limiter);
```

**Comment by aksharj** [comment]
Hi @nfriedly, thanks a lot for quick reply. That fixed it. :)
