### ISSUE TITLE
how can I override the rate limiter function

### ISSUE THREAD

**Issue by thomasInes** [nfriedly/express-rate-limit#203]
Hi :)
More a question than a bug. Im trying to wrap the rate limiter function in a custom function so I can use different values for `windowMs` and `max`. 
Im not sure of the implementation so I did this, and the my middleware function just runs indefinitely without going to the next function.
I was wondering what Im trying is possible technically.
Thanks for your help

eg.

```js
const rateLimit = require('express-rate-limit');

const customRateLimiter = (req,res,next) => {
  let maxRequestWindow = 111111; // some value
  let maxRequestLimit = 1111; // some value

  if(/** some condition **/){
    maxRequestWindow =  666666; // another value
    maxRequestLimit =  6666; // another value
  }

  return rateLimit({
    windowMs: maxRequestWindow,
    max: maxRequestLimit
  });
}

app.get('/test', customRateLimiter,  (req, res)=>{
  return res.send('ok');
});
```

**Comment by nfriedly** [comment]
I think the trick is that you need to call customRateLimiter() once, when the script initializes  - it's currently calling it again and again for each new request. Try this:

```js
const rateLimit = require('express-rate-limit');

const customRateLimiter = () => { // removed req,res,next
  let maxRequestWindow = 111111; 
  let maxRequestLimit = 1111; 

  if(/** some condition **/){
    maxRequestWindow =  666666;
    maxRequestLimit =  6666;
  }

  return rateLimit({
    windowMs: maxRequestWindow,
    max: maxRequestLimit
  });
}

app.get('/test', customRateLimiter(),  (req, res)=>{ // added ()
  return res.send('ok');
});
```

I'll also mention that the `max` param is allowed to be a function that returns a different number (or a promise that resolves to a number) for each visitor. But, `windowMs` has to be a fixed value, so it may be a moot point for you.
