### ISSUE TITLE
How to send correct error response to front end

### ISSUE THREAD

**Issue by RokasDie** [nfriedly/express-rate-limit#204]
Hello, I am having issues how to use this library for error handling in front end.

So in the backend I have this limiter setup: 

```
const commentCreationRateLimit = rateLimit({
    windowMs: 30 * 60 * 1000, 
    max: 2,
    statusCode: 429,
    message: { error: 'Too many comment create requests' }
});

router.post(
        '/new-comment',
        commentCreationRateLimit,
```

Now after the limit is hit in the front if I try to access err.message, I only get "Request failed with status code 429". However, I have no way to access the custom message which I created

**Comment by nfriedly** [comment]
Hi @RokasDie,

I couldn't really say without knowing more about your front-end code. It sounds like it's automatically creating an error object for these responses, and perhaps your front-end code drops the body of the response, or perhaps it's provided in a different argument.

One alternative could be to use a 200 status code and then check the response to see if it contains an error message or not. It's not the _best_ way to handle things, but it may be good enough to get you unblocked.

**Comment by wildan3105** [comment]
Sorry just to chime in, I've configured custom error message before. So I think you can do something like this:

```javascript
const commentCreationRateLimit = rateLimit({
    windowMs: 30 * 60 * 1000, 
    max: 2,
    statusCode: 429,
     message: {
        error_code: 'TOO_MANY_REQUESTS',
        message: '<Your custom error message>'
    }
});
```

This way, I believe you can access `err.message` with your own custom message @RokasDie
