### ISSUE TITLE
Nginx reverse proxy

### ISSUE THREAD

**Issue by ultrasamad** [nfriedly/express-rate-limit#205]
Hello, my app is behind an Nginx reverse proxy and I have this `app.set('trust proxy', 1)` before the rate-limit middleware.
But when I checked my redis store I realized the ip address that's being tracked rather is `ffff:127.0.0.1` and not the real client ip address. Do I need to set up additional configurations?

Thanks

**Comment by nfriedly** [comment]
It should be `trust proxy`, not `reverse proxy` ([express docs](https://expressjs.com/en/guide/behind-proxies.html)) - Do my docs say "reverse" somewhere?

**Comment by ultrasamad** [comment]
@nfriedly Sorry it's a typo. In my app it is actually `app.set('trust proxy', 1)`

**Comment by ultrasamad** [comment]
This is a snippet from my server script:
```
app.set('trust proxy', 1);
const limiter = rateLimit({
    store: new RedisStore({
        prefix: 'myapp',
    }),
    windowMs: 24 * 60 * 60 * 1000,
    max: 10,
    message: 'You have exceeded your free quota for the day',
    //delayMs: 0
});
```
and my Nginx configuration
```
location / {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
    }
```

**Comment by nfriedly** [comment]
I think you also have to configure nginx to pass along the data:

```
proxy_set_header Forwarded $proxy_add_forwarded;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

(You probably only need one of those, but setting both shouldn't hurt anything.)

See more at https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

**Comment by ultrasamad** [comment]
> I think you also have to configure nginx to pass along the data:
> 
> ```
> proxy_set_header Forwarded $proxy_add_forwarded;
> proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> ```
> 
> (You probably only need one of those, but setting both shouldn't hurt anything.)
> 
> See more at https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/

@nfriedly Thanks very much for the help. 
Setting the `X-Forwarded-For` header solved the issue.
The first snippet seem to be throwing some ngnix syntax errors. So the second one did the trick.

**Comment by gagan-bansal** [comment]
Along @nfriedly answer, this module [request-ip](https://www.npmjs.com/package/request-ip) is also very helpful.

**Comment by nadirzebiri** [comment]
Alond @nfriedly answer, I had to renew my SSL certificate from Certbot to make it work
