### ISSUE TITLE
X-Ratelimit-Remaining is being reset after page reload

### ISSUE THREAD

**Issue by badgersmans** [nfriedly/express-rate-limit#206]
I recently noticed that the header X-Ratelimit-Remaining is reset upon a page refresh

Is this a bug?

this is how I set it up, pretty standard.

```
const limiter = rateLimit({
    max: 3,
    windowMs: 60 * 60 * 1000,
    message: {
        message: "Too many login attempts, try again in 1 hour"
    }
});

if(process.env.NODE_ENV === 'production') {
    app.use('/api/users/login', limiter);
}
```

it works only when I don't reload the page, however if I reload the page, then I can have infinite logins.

So I can infinite login by login > logout > refresh page > login > logout > refresh page > login and so on...

EDIT: You don't even have to refresh, just wait a while...and it will work again.

I set it to wait for 1 hour, but before 1 hour ends, I could still login...

EDIT: Same behavior on Postman, you wait a while, and you could login again.

Maybe it's my middleware stack?

```
// middlewares
app.use(helmet);
app.use(express.json());
app.use(mongoSanitize());
app.use(xss());
app.use(morgan());

then the limiter middleware...
```

**Comment by nfriedly** [comment]
That's definitely odd. Do you happen to have more than one process (via the cluster module or multiple servers or some kind of serverless thing)? If so, you'll want to have a custom store in order to get consistent results.  Since it looks like you're already using mongodb, you might want to try out https://www.npmjs.com/package/rate-limit-mongo 

(It will still thwart attackers eventually without the custom store, it'll just take a little longer because each server/process has to hit the limit individually, and the results will be inconsistent until they all do.)

**Comment by badgersmans** [comment]
I've tried rate-limit-mongo but couldn't get it to work, the documentation didn't give an example on what i should put in the options...

could you give me an example of how to use the rate-limit-mongo? thanks 👍

**Comment by nfriedly** [comment]
I've never actually used it, but it does have the configuration documented right below the example. I'd guess you'd probably want something like this:

```js
var RateLimit = require('express-rate-limit');
var MongoStore = require('rate-limit-mongo');
 
var limiter = new RateLimit({
  store: new MongoStore({
    uri: "mongodb://127.0.0.1:27017/test_db",
    user: "mongouser",
    password: "mongopassword"
    errorHandler: console.error.bind(null, "rate-limit-mongo"), 
  }),
  max: 100,
  windowMs: 15 * 60 * 1000
});
 
//  apply to all requests
app.use(limiter);
```

**Comment by badgersmans** [comment]
what's the benefit of using a custom store instead of the memory store?

does it solve the inconsistency I'm seeing?

**Comment by nfriedly** [comment]
> Do you happen to have more than one process (via the cluster module or multiple servers or some kind of serverless thing)? If so, you'll want to have a custom store in order to get consistent results.

If there is more than one node.js process, then the store will allow them to maintain consistency. Otherwise they all do their own thing and will each eventually block anyone who's really pushing the limits, but you'll get undefined behavior until they _all_ reach the limit.

**Comment by badgersmans** [comment]
thanks for the example, after using mongo store, it seems that the behavior is now consistent! and I love the fact that it stores it in my database, that way it's reliable. Thanks for your help!

**Comment by nfriedly** [comment]
Glad it's working for you now :)
