### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by Piccirello** [nfriedly/express-rate-limit#209]
I'm working on a new feature in our app that requires `express-rate-limit` to be able to support an async `skip` function. More specifically, we're checking a Redis key to determine if the request should be counted against the limit.

I see that support for this was added back in May in 5a8687269f685ebf0a37574a2a680c8f8809dcdb (yay!), however this change hasn't been released yet. Are there any plans to release a new version with this change?

**Comment by nfriedly** [comment]
Oh, shoot, I forgot to do that! Thanks for the reminder. v5.2.0 should be published to npm shortly

**Comment by nfriedly** [comment]
Done now, v5.2.3. 

(There ended up being a few 5.2.x builds published to npm, as I was having trouble with the CI system. But they're all the same code.)

**Comment by Piccirello** [comment]
Thanks @nfriedly for the quick release!
