### ISSUE TITLE
express deprecated res.send(status): Use res.sendStatus(status) instead...

### ISSUE THREAD

**Issue by MrPurpose** [nfriedly/express-rate-limit#213]
I'm receiving this warning on my serverside:

> express deprecated res.send(status): Use res.sendStatus(status) instead node_modules\express-rate-limit\lib\express-rate-limit.js:23:40

Am I supposed to handle the fix for this error directly on my installed package? Not sure how to proceed, I'm in my early days of coding.

**Comment by nfriedly** [comment]
I don't think that should be happening.. did you maybe put a number in for the `message` option? Or, can you post your code?

**Comment by MrPurpose** [comment]
oooh dude, It was exactly that, I was sending a number (429) as a message.
Sorry for the trouble. 😅 
I appreciate the attention, thank you.
