### ISSUE TITLE
User rate-limited in the first request

### ISSUE THREAD

**Issue by NimaAliNejad** [nfriedly/express-rate-limit#215]
Hi
I have 4 API Servers with same functionality and approx 2 milion users, clients send the request to the AWS LoadBalancer that have these 4 Servers and each of these API Servers executing API node application in cluster mode set to max (all of the cores, in my case 8 cores).
everything was okay since 2 weeks ago but when suddenly my users grew up and it happen to users get 429 error and X-RateLimit-Remaining: 0 in their first request ,i had to make the bellow change to make the error happen once per every 10 requests (probably but its random) 
```
const limiter = rateLimit({
  windowMs: 1000, 
  max: 4,
  delayMs:0
});

const meRateLimiter = rateLimit({
  windowMs: 1000, 
  max: 3, 
  delayMs:0
});

const takeRateLimiter = rateLimit({
  windowMs: 1000, 
  max: 4, 
  delayMs:0
});

app.use("/hi",limiter);
app.use("/zone",limiter);
app.use("/me",meRateLimiter);
app.use("/take",takeRateLimiter);
```

to

```
const limiter = rateLimit({
  windowMs: 1000, 
  max: 6,
  delayMs:0
});

const meRateLimiter = rateLimit({
  windowMs: 800,
  max: 5, 
  delayMs:0
});

const takeRateLimiter = rateLimit({
  windowMs: 800, 
  max: 6, 
  delayMs:0
});

app.use("/hi",limiter);
app.use("/zone",limiter);
app.use("/me",meRateLimiter);
app.use("/take",takeRateLimiter);
```

but i'm going to trouble from last night again

**Comment by nfriedly** [comment]
Do you have `app.set('trust proxy`, true)` configured appropriately? See https://expressjs.com/en/guide/behind-proxies.html

Also, since you're using the default store, each cluster worker is keeping it's own list of IP's to rate-limit; you probably want to use an external proxy so that they can all coordinate with each other.

**Comment by RunsetTech** [comment]
Api is not behind proxy, so i need setup proxy to fix this issue ?

**Comment by nfriedly** [comment]
Load balancers are a type of proxy

**Comment by nfriedly** [comment]
Oh, I just saw that I wrote "external proxy" when I meant to say "external store". Sorry about that. I edited the comment to be correct now

**Comment by RunsetTech** [comment]
so if i add this line 
app.set('trust proxy', true)
to the script probably it wil fix the issue ?
what kind of external store do you suggest ?
thanks for your awesome answers

**Comment by nfriedly** [comment]
I think so. Assuming it works you might want to change `true` to `1`:
```diff
- app.set('trust proxy', true)
+ app.set('trust proxy', 1)
```
That makes it a bit more secure. You can read their docs for more info.

Ask for the store, there are a few listed in the readme: https://github.com/nfriedly/express-rate-limit#stores - and probably some more that I don't know about. I'd generally recommend redis or memcache, but if you're already running an existing data store then it probably makes sense to use that.

**Comment by RunsetTech** [comment]
I'm using the default store, i think i should go for your sugegstions. thanks for your great replies, i wil try them

**Comment by RunsetTech** [comment]
I made the below changes but same behaviour as before (now its happening even more), i wonder why this is happening
i've double checked everything unfortunately i didn't get the reason :(

```
app.set('trust proxy', 1);

const redis = require("redis");
const RedisStore = require('rate-limit-redis');
const RateLimit = require("express-rate-limit");



const redisPort = 6379
const client = redis.createClient(redisPort);

//log error to the console if any occurs
client.on("error", (err) => {
    console.log(err);
});

const limiter = new RateLimit({
  store: new RedisStore({
    expiry:1,
    client: client
  }),
  max: 6,
  delayMs: 0
});

const meRateLimiter = new RateLimit({
  store: new RedisStore({
    expiry:1,
    client: client
  }),
  max: 5,
  delayMs: 0
});

const takeRateLimiter = new RateLimit({
  store: new RedisStore({
    expiry:1,
    client: client
  }),
  max: 6,
  delayMs: 0
});
```

**Comment by RunsetTech** [comment]
req.connection.remoteIp doesn't return the client ip and it return the loadbalancer ip even i added the app.set('trust proxy', 1);
but req.headers['x-forwarded-for'] return the actual client ip so how can i change the remoteIp in the middleware before rate-limiter to use it ?

**Comment by nfriedly** [comment]
You might want to specify a different prefix for each of the stores and/or increase the limit further. Previously it was 3-4 requests per limiter per worker, so an end user could make a lot of requests before hitting any limit. Now it's 6 across all limiters and workers, so it makes sense that someone would hit it faster.

**Comment by RunsetTech** [comment]
The main problem is users get rate limited on their first request or get X-rate-limit: 1 while i've set it 5 reqs per 1 second. I tested it many times and its limit me even after the specified time (1 second) passed.

**Comment by nfriedly** [comment]
Hum, I'm not sure. There's definitely something not right, but I'm not sure what :/

**Comment by RunsetTech** [comment]
Seems the issue was with app.set('trust proxy', 1) it was not working properly and req.ip sometimes return client ip and sometimes return LoadBalancer ip, i've changed it to app.set('trust proxy', true) now req.ip returns client ip all the time. I hope the situation stay in this way.
