### ISSUE TITLE
TypeError: this.__buildConfiguration is not a function

### ISSUE THREAD

**Issue by sourikghosh** [nfriedly/express-rate-limit#218]
I am using `nodejs 14.15.4` and `es module import`:
### while using
```bash
import rateLimiter from 'express-rate-limiter'
```
or 
```bash
import {rateLimiter} from 'express-rate-limiter'
```
### Error
```bash
this.__configuration = this.__buildConfiguration(options);
                                ^

TypeError: this.__buildConfiguration is not a function
    at module.exports
```

**Comment by nfriedly** [comment]
I'm not sure.. does it work if you use `require()` instead of `import`?

**Comment by sourikghosh** [comment]
@nfriedly I don't know it didn't work for me...

**Comment by amagid** [comment]
So, I just ran into this exact issue and found that I had mistakenly installed `express-rate-limiter` rather than `express-rate-limit`.

Installing `express-rate-limit` fixed the issue.
