### ISSUE TITLE
Apply to all requests with use but also retrieve req object

### ISSUE THREAD

**Issue by bacloud14** [nfriedly/express-rate-limit#220]
How can I set rate-limit on all requests (get/post, ...) on all endpoints but retrieve especially `req` object so I can do some analysis.

Trying:

```
router.use(useragent.express());
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100,
  headers: true
});
router.use(apiLimiter, function(req,res){});
```

with the handler function(req,res){} makes errors, as just one request after server restart yields an error like rate limit has been exceeded.

and same for 
`router.use("/", apiLimiter, function(req,res){});`
or
`router.get("/", apiLimiter, function(req,res){});`

byt the way

**Comment by nfriedly** [comment]
I think this is what you want:

```js
router.use(useragent.express());
const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100,
  headers: true,
  handler: function(req, res){
    // this gets called for each request after the user has exceeded their limit.
    // you can inspect `req` here
    res.status(429).send("too many requests");
  }
});
router.use(apiLimiter);
```

Or did I mis-understand your question?

Note that functions passed to `router.use()` usually accept a `next()` param like so:

```js
router.use(function (req, res, next) { 
  // do stuff
  next();
});
```

**Comment by bacloud14** [comment]
That was is it. thank you so much !
I mistaken putting handler in `use` function.
