### ISSUE TITLE
Limit doesn't work when the middleware is used with app.use args

### ISSUE THREAD

**Issue by iamkenos** [nfriedly/express-rate-limit#221]
Hi! Thanks for bringing us this middleware. I'm getting a weird issue, described below.

From what I observed, it looks like for some reason, the memory store doesn't work properly when the middleware is used like so:

```
app.use((req, res, next) =>
  limit({
    windowMs: 1000,
    max: req.body.data.limit,
    handler: (req, res, next) => {
      res.status(req.body.data.status);
      res.send(req.body.data.message);
    },
  })(req, res, next)
);
```

Couldn't exactly understand why. The X-Rate headers are still being applied but the hit counters aren't saved properly

node version: `v12.18.3`
express version: `4.17.1`
limit version: `5.2.3`

[Here's a repo](https://github.com/iamkenos/express-rate-limit-issues) showing the issue.

**Comment by nfriedly** [comment]
Hi @iamkenos 

That looks like you're creating a new instance of express-rate-limit for each request. So, each request gets a new memory store with zero history.

Instead you need to something like this:


```js
app.use(
  limit({
    windowMs: 1000,
    max: (req, res) => req.body.data.limit,
    handler: (req, res, next) => {
      res.status(req.body.data.status);
      res.send(req.body.data.message);
    },
  })
);
```

Although, I will point out that pulling the max out of the `req.body.data` seems wrong.. are you intending to let the requester choose their limit? And their error message, for that matter?

**Comment by iamkenos** [comment]
cool! that works! thanks! 🥳 

`req.body.data` this part was just for illustration, but ultimately, yea, that's the intention 😅 
i'm using this together with a mocking framework to simulate some weird cases with a rate-limited api.

thanks again for the quick feedback!!
