### ISSUE TITLE
FeatureRequest: Support multiple plans

### ISSUE THREAD

**Issue by AlexShkunov** [nfriedly/express-rate-limit#227]
Currently, config <max> is applied to all requests.

Need to support on-demand config, ie. User Joe is premium and thus has max 10, User Billy is basic and thus has max 5

**Comment by nfriedly** [comment]
Hi @AlexShkunov 

The `max` setting may be a function that returns a number or a promise that resolves to a number. For example:

```js
const rateLimit = require("express-rate-limit");

function isPremium(req) {
  //...
}

const limiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: function(req, res) {
    if (isPremium(req)) {
      return 10;
    }
    return 5;
  }
});

//  apply to all requests
app.use(limiter);
```

Would that work for your use case?

**Comment by AlexShkunov** [comment]
Thank you for the quick reply.

Just to confirm - "max" Function is invoked on Every request (so if DB value changes - it gets reflected)?
https://github.com/nfriedly/express-rate-limit/blob/master/lib/express-rate-limit.js#L71

What about windowMs? E.g. One profile has 5 per minute, the other has 20 per hour?

**Comment by nfriedly** [comment]
Yea, `max` is checked for every request. 

Unfortunately, `windowMs` has to be a fixed value in the current design, because some stores (including the default one) group requests into a bucket rather than creating different timers for every single request.
