### ISSUE TITLE
Ratelimits all IPs because of heroku proxy on Next.js

### ISSUE THREAD

**Issue by ExordiumX** [nfriedly/express-rate-limit#230]
How do I enable proxies so this middleware can work on Next.js API?

**Comment by nfriedly** [comment]
```js
// see https://expressjs.com/en/guide/behind-proxies.html
app.set('trust proxy', 1);
```

If `1` doesn't work try a higher number or just `true`.

**Comment by DanDev95** [comment]
That's for Express.js though. Next.js uses it's own server.

**Comment by nfriedly** [comment]
I thought next.js used express under the hood (?)

**Comment by DanDev95** [comment]
Probaby, but there is no "app" that you can run .set on.

**Comment by nfriedly** [comment]
Check this out: https://github.com/vercel/next.js/tree/master/examples/with-custom-reverse-proxy
