### ISSUE TITLE
use api key instead of ip address 

### ISSUE THREAD

**Issue by pgamerxdev** [nfriedly/express-rate-limit#231]
I want to use api key instead of ip address so as to provide them with more detailed analytics

**Comment by nfriedly** [comment]
You'll want to pass in a function for the `keyGenerator` config option that returns the API key instead of the ip:

https://github.com/nfriedly/express-rate-limit#keygenerator

**Comment by pgamerxdev** [comment]
> You'll want to pass in a function for the `keyGenerator` config option that returns the API key instead of the ip:
> 
> https://github.com/nfriedly/express-rate-limit#keygenerator

can you explain?

**Comment by nfriedly** [comment]
Yea, here's example that pulls the API key from a querystring param named `api_key`. So, if the url was `http://example.com/foo?api_key=bar`, this would use `bar` instead of the requester's IP.

```js
const rateLimit = require("express-rate-limit");

app.use(rateLimit({
  // ...
 keyGenerator: function(req, res) {
    // uses api_key from querystring if present, fall back to ip otherwise
    return req.query.api_key || req.ip;
 },
}));
```

Obviously you'd want to check that the API key is present and valid, and return an error message otherwise, but that would be outside of this module. But, with the fallback to an IP address, you can perform that check after rate-limiting. (This could be helpful if checking an API key involved a database lookup of something else moderately expensive.)

**Comment by pgamerxdev** [comment]
> Yea, here's example that pulls the API key from a querystring param named `api_key`. So, if the url was `http://example.com/foo?api_key=bar`, this would use `bar` instead of the requester's IP.
> 
> ```js
> const rateLimit = require("express-rate-limit");
> 
> app.use(rateLimit({
>   // ...
>  keyGenerator: function(req, res) {
>     // uses api_key from querystring if present, fall back to ip otherwise
>     return req.query.api_key || req.ip;
>  },
> }));
> ```
> 
> Obviously you'd want to check that the API key is present and valid, and return an error message otherwise, but that would be outside of this module. But, with the fallback to an IP address, you can perform that check after rate-limiting. (This could be helpful if checking an API key involved a database lookup of something else moderately expensive.)

Thank you! 
So for me it will be something like 
```js
req.get("x-api-key") || req.ip
// I am using header 
```

**Comment by thanhnguyennguyen** [comment]
can we set rate limit for given api_key ?

example:

api_key_A : rate 1000 request / day
api_key_B : rate 5000 request / day

**Comment by nfriedly** [comment]
@thanhnguyennguyen Yes, that is possible. Something like this:

```js
const rateLimit = require("express-rate-limit");

const limiter = rateLimit({
  windowMs: 24 * 60 * 60 * 1000, // 1 day
  
  // max could also be an async function or return a promise
  max: function(req, res) {
    if (req.query.api_key === 'api_key_A')
      return 1000;
    }
    if (req.query.api_key === 'api_key_B')
      return 5000;
    }
    // fallback
    return 1
});

//  apply to all requests
app.use(limiter);
```
