### ISSUE TITLE
Add a way to specify the duration of the rate limit separately

### ISSUE THREAD

**Issue by DaisyDogs07** [nfriedly/express-rate-limit#235]
I think it would be nice to optionally set the duration of the rate limit so there can be more customization to it :)

**Comment by nfriedly** [comment]
I understand the desire, and the original version did allow for that, but removing the feature allowed for a pretty significant performance & memory optimization for the built-in MemoryStore. 

In most cases, setting a per-user *limit* (which is supported), can offer effectively the same result. 

If, you find that you *need* to be able to set the duration per-user, though, then you should try out one of the alternative libraries linked to in the readme.

**Comment by DaisyDogs07** [comment]
Oh, Ok.
