### ISSUE TITLE
express-rate-limit ip error in vercel

### ISSUE THREAD

**Issue by chaaawles** [nfriedly/express-rate-limit#236]
I already added the `app.set('trust proxy', true);` but  it still throws the error _Too many requests, please try again later._ Is there a workaround in this error?

**Comment by nfriedly** [comment]
I'm not sure... Try adding an endpoint like so:

```js
app.get('/headers', (req, res) => res.json(req.headers) );
```

And then go to that endpoint (http://your-app.com/headers) and see if there are any `x-forwarded-for` headers present. That's what the trust proxy setting uses.

**Comment by atawfique21** [comment]
For those deploying a Next.js app with Vercel, you'll want to refer [here](https://vercel.com/docs/edge-network/headers). 

To rate limit through Vercel, you must use:
`keyGenerator: function (req) {
    return req.headers["x-real-ip"];
  }`
Inside of your rateLimit function. 

`x-real-ip` is the equivalent of `x-forwarded-for`.
