### ISSUE TITLE
Using with cloudflare

### ISSUE THREAD

**Issue by NoodlesDev987** [nfriedly/express-rate-limit#238]
How to use this with cloudflare?
I have added `app.set('trust proxy', 1);` to code,  but it still don't work well.
I think that cloudflare is sending original request ip in headers

**Comment by nfriedly** [comment]
> I think that cloudflare is sending original request ip in headers

That's what the `trust proxy` setting is for, it parses the headers and uses that IP.

The `1` means it will only tryst the nearest proxy, there may be multiple. Make an endpoint that shows the headers and look at the `X-Forwarded-For` header (what express uses), and compare it to your actual IP. You can also look at `CF-Connecting-IP` for comparison:

```js
app.get('/headers', (req, res) => res.json({req.headers));
```
Then increment as necessary to get the actual client's IP.

See http://expressjs.com/en/guide/behind-proxies.html and https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-

**Comment by NoodlesDev987** [comment]
Yes, the real ip is in CF-Connecting-IP header, so how to set express-rate-limit to get the ip from the header?

**Comment by nfriedly** [comment]
That's strange that you're not getting the `X-Forwarded-For` header, but oh well. 

To use `CF-Connecting-IP`, set the [keyGenerator](https://github.com/nfriedly/express-rate-limit#keygenerator) option to a function like so:

```js
const limiter = rateLimit({
  // other config here...
  keyGenerator: function (req /*, res*/) {
    return req.headers['cf-connecting-ip'] || req.ip;
  }
});
```

That will use the header if it's available, and fall back to the IP if not. (I didn't test that, but it should at lest give you the right idea.)
