### ISSUE TITLE
Not working with express.Router()

### ISSUE THREAD

**Issue by ErcouldnT** [nfriedly/express-rate-limit#239]
Hi, my main app.js commands is like that:
```js
app.use('/api/v1/user', userApi);
app.use('/api/v1/room', roomApi);
app.use('/api/', middlewares.apiLimiter);
app.use('/api/', middlewares.speedLimiter);
```
and both middlewares are not working on /api routes which is express.Router() routes.

**Comment by nfriedly** [comment]
I think you need to change the order so that the limiters come before the routes.

**Comment by ErcouldnT** [comment]
So, it works! I sometimes can't believe myself. Thanks!

**Comment by nfriedly** [comment]
No worries, glad it's working for you now :-)
