### ISSUE TITLE
I want to verify api key on each request and allow accordingly

### ISSUE THREAD

**Issue by AhsanAshfaq** [nfriedly/express-rate-limit#240]
Let's say we have implemented like following.

```
const rateLimit = require("express-rate-limit");

app.use(rateLimit({
  // ...
 keyGenerator: function(req, res) {
    // uses api_key from querystring if present, fall back to ip otherwise
    return req.query.api_key || req.ip;
 },
}));
```

Now suppose we have two different api keys and we want to give different request limit to each api key. 

1- APIKEY1 --- should be allowed to make 100 request 
2- APIKEY2 ---- should be allowed to make 10 request

So i want to know that is there any hook we can implement to check the api key on every request and check their count as well so that we can restrict when needed.

**Comment by nfriedly** [comment]
Yes, you can do that -  the [max](https://github.com/nfriedly/express-rate-limit#max) configuration option can be set to a function rather than a number, and then it can return different limits for different api keys. For example:

```js
const rateLimit = require("express-rate-limit");

app.use(rateLimit({
 // ...
 max: function(req, res) {
   // set the number of requests allowed based on the API key used
   if (req.query.api_key === 'APIKEY1') {
     return 100;
   } else if (req.query.api_key === 'APIKEY2') {
     return 10;
   } else {
     return 0;
   }
 },
 keyGenerator: function(req, res) {
    // uses api_key from querystring if present, fall back to ip otherwise
    return req.query.api_key || req.ip;
 },
}));
```

You can also use an `async` function or return a `Promise` that eventually resolves to a number if you need to do a database lookup or whatever.

**Comment by AhsanAshfaq** [comment]
> Yes, you can do that - the [max](https://github.com/nfriedly/express-rate-limit#max) configuration option can be set to a function rather than a number, and then it can return different limits for different api keys. For example:
> 
> ```js
> const rateLimit = require("express-rate-limit");
> 
> app.use(rateLimit({
>  // ...
>  max: function(req, res) {
>    // set the number of requests allowed based on the API key used
>    if (req.query.api_key === 'APIKEY1') {
>      return 100;
>    } else if (req.query.api_key === 'APIKEY2') {
>      return 10;
>    } else {
>      return 0;
>    }
>  },
>  keyGenerator: function(req, res) {
>     // uses api_key from querystring if present, fall back to ip otherwise
>     return req.query.api_key || req.ip;
>  },
> }));
> ```
> 
> You can also use an `async` function or return a `Promise` that eventually resolves to a number if you need to do a database lookup or whatever.

It worked for me .. Thanks
