### ISSUE TITLE
Feature Request: One counter for all api path

### ISSUE THREAD

**Issue by kirtanparmar9** [nfriedly/express-rate-limit#242]
Currently counter work separately for each path. Is it possibly to make it global by key/ip ?
  
My simple requirement is that rate limit counter should work based on user IP or Key instead of separate counter for each api path

E.g 
max: 100
windowMs: 60000
paths:   api/path1,  api/path3,  api/path3

User should able to send max 100 request only in one minute, doesn't matter whichever path they use

**Comment by nfriedly** [comment]
Hi @kirtanparmar9 

I can't say for sure without seeing your code, but it sounds like you're creating a new instance for each path (?)

If you use the same instance of express-rate-limit for all paths, then the counter should work the way you want.

For Example:

```js
const rateLimit = require("express-rate-limit");

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100
});

app.use("/api/path1", apiLimiter);
app.use("/api/path2", apiLimiter);
app.use("/api/path3", apiLimiter);
```

Or, more simply, apply it to all requests going to /api/*


```js
const rateLimit = require("express-rate-limit");

const apiLimiter = rateLimit({
  windowMs: 15 * 60 * 1000, // 15 minutes
  max: 100
});

app.use("/api/", apiLimiter);
```
