### ISSUE TITLE
Rate-limiting works in browser but not when fetching with code

### ISSUE THREAD

**Issue by VeryHamburger** [nfriedly/express-rate-limit#243]
Today I found out that rate-limiting only works in browser, not when fetching with code.

**Code I used to test:**
![rKerq5CPL7](https://user-images.githubusercontent.com/72227790/125198554-32ac0380-e25a-11eb-9039-07580b75011b.png)

**Output:**
![image](https://user-images.githubusercontent.com/72227790/125198581-50796880-e25a-11eb-919c-fd3f8e29dd2e.png)

It should ratelimit but it doesn't. Only happens in browser but I want it to do both.

**Example API Code:**
![lzsU8jsI7a](https://user-images.githubusercontent.com/72227790/125198635-9cc4a880-e25a-11eb-8c96-f5c85ab1aa6d.png)

Sometimes works when I set `max` (maximum requests) to 5. Here's the output:
![XC6J4qxxsG](https://user-images.githubusercontent.com/72227790/125234377-80675100-e2d8-11eb-9ebc-dd59a478a15f.png)

Am I doing something wrong or is it not supposed to ratelimit when fetching with code?

**Comment by nfriedly** [comment]
No, the ratelimit should apply either way. It doesn't look like you're hitting the same server though. The one that is working is getting the expected 'API is ACTIVE' reply when not limited, but the other one is getting some JSON with a link, as if it's connecting to a completely different app.

**Comment by jaipack17** [comment]
@VeryHamburger Those are two different servers, try sending requests to your main server.

**Comment by VeryHamburger** [comment]
@nfriedly The first screenshot which includes "https://test-api.nitcord.repl.co/" is a fork of "https://animality.xyz/". Forgot to change it when creating an issue. Below you can see the screenshot that replace the first screenshot.

**Updated screenshot:**
![dmYkzKH72s](https://user-images.githubusercontent.com/72227790/125304316-6738c180-e325-11eb-9c58-e8acaabcb9f3.png)

**Comment by nfriedly** [comment]
Ok, well, my guess is that there's either no rate limit or a more relaxed rate limit on api.animality.xyz

**Comment by jaipack17** [comment]
> Ok, well, my guess is that there's either no rate limit or a more relaxed rate limit on api.animality.xyz

So I tested this out for myself. And it turns out, when setting `max` to 5 requests per ip per minute, it works and does rate-limit me, but when setting it to 50 requests per ip per minute, it does not seem to work. Code samples: 

```js
const express = require('express');
const fs = require('fs');
const rateLimit = require("express-rate-limit");

const app = express();

const limiter = rateLimit({
  windowMs: 60000, 
  max: 5,
  message: {
    error: "rate limitted"
  },
});

app.use(limiter);
app.enable('trust proxy', 1);
app.use(express.static('public'));

app.get('/', limiter, async (req, res) => {
    return res.send({
      success: "api online"
    })
});

app.listen(process.env.PORT, () => console.log('Your server is alive!'));
```
![image](https://user-images.githubusercontent.com/74130881/125310891-9d3f6b00-e350-11eb-8fbc-ba5b9552dcf3.png)

While setting `max` to 50 does not work - 

![image](https://user-images.githubusercontent.com/74130881/125311028-b811df80-e350-11eb-9087-0a6e9dd0d88c.png)

Testing requests - 

```js
const axios = require("axios");
const base = "https://ratelimit.jaipack17.repl.co";

async function get() {
    await axios({
        method: 'get',
        url: base,
        responseType: 'json'
    }).then(res => {
        console.log(res.data);
    })
}

var a = 0;

while (a != 500) {
    get();
    a++;
}
```

**Comment by nfriedly** [comment]
So, it looks like there's only ~40 requests in your second screenshot. If the limit is 50, then that's to be expected.

Also, the way it works, if you happen to get 50 requests in right before the server's clock ticks, and 50 right after, then it'll look like 100 requests in a row were allowed. That would really be 100 requests across two minutes, so it's still 50/minute, but the point is that it may appear to give > 50 requests before limiting you. If you keep it up for a few minutes, though, it'd quickly become apparent that the 50/minute limit is being enforced.

All I'm trying to say is that I don't see any problem here. Everything appears to be working correctly.

**Comment by VeryHamburger** [comment]
> So, it looks like there's only ~40 requests in your second screenshot. If the limit is 50, then that's to be expected.
> 
> Also, the way it works, if you happen to get 50 requests in right before the server's clock ticks, and 50 right after, then it'll look like 100 requests in a row were allowed. That would really be 100 requests across two minutes, so it's still 50/minute, but the point is that it may appear to give > 50 requests before limiting you. If you keep it up for a few minutes, though, it'd quickly become apparent that the 50/minute limit is being enforced.
> 
> All I'm trying to say is that I don't see any problem here. Everything appears to be working correctly.

So there is nothing wrong with the code and everything works?

**Comment by nfriedly** [comment]
Yea, the only think I would caution you about there is the `app.enable('trust proxy');` - that causes it to trust an unlimited number of `X-Forwarded-For` headers, which means a malicious actor can just add their own header with a random IP and get effectively unlimited use of your API.

You should do `app.enable('trust proxy', 1);` and change the `1` to the number of proxies between your API and the internet. 

If you're not sure how many proxies are between your API and the internet, you can test it by setting up an endpoint like so:

```
app.get('/ip', (req, res) => res.send(req.ip));
```

Then compare the results of that to your actual IP (http://ip.nfriedly.com/text will give you your actual IP). First try commenting out the `app.enable('trust proxy');` and see if the numbers match, then try it with `1`, `2`, etc. Pick the lowest number that lets it show your actual IP. That's the number where it will work without leaving you vulnerable.

**Comment by VeryHamburger** [comment]
What if I'm using a host like Replit?

**Comment by nfriedly** [comment]
Yea, that's when you'll have to experiment to figure out how many proxies are between your API and the internet. The answer is *probably* `1`, but I can't say for sure.

**Comment by VeryHamburger** [comment]
I see different IPs when I increase the number.

**Comment by nfriedly** [comment]
At what point do you see *your* IP. 

http://ip.nfriedly.com/text will tell you your IP.

**Comment by VeryHamburger** [comment]
Adding the code below shows an IP. When I change `app.set('trust proxy', 1);` to `app.set('trust proxy', 2);`, it shows different IPs

```app.get('/ip', (req, res) => res.send(req.ip));```

**Comment by nfriedly** [comment]
Hum.. that's confusing. Maybe you're behind CGNAT, which means that you don't really have an IP, you're just sharing a pool of IPs with other people (?)

Where does it show the ISP?

**Comment by VeryHamburger** [comment]
I used a site to check the ISP.

**Comment by VeryHamburger** [comment]
> So, it looks like there's only ~40 requests in your second screenshot. If the limit is 50, then that's to be expected.
> 
> Also, the way it works, if you happen to get 50 requests in right before the server's clock ticks, and 50 right after, then it'll look like 100 requests in a row were allowed. That would really be 100 requests across two minutes, so it's still 50/minute, but the point is that it may appear to give > 50 requests before limiting you. If you keep it up for a few minutes, though, it'd quickly become apparent that the 50/minute limit is being enforced.
> 
> All I'm trying to say is that I don't see any problem here. Everything appears to be working correctly.

@jaipack17 said that its just a part of the console. In reality, those were 500 requests spammed by his console.

**Comment by nfriedly** [comment]
Oh, I did miss that. 

The fact that it never shows your IP is really confusing. I think that probably has the same root cause as the rate-limit not applying when you'd expect it to.

**Comment by VeryHamburger** [comment]
> Oh, I did miss that.
> 
> The fact that it never shows your IP is really confusing. I think that probably has the same root cause as the rate-limit not applying when you'd expect it to.

It could be because of Replit's integrated proxy. They take care of the proxy for the machine I'm using.

**Comment by VeryHamburger** [comment]
> Yea, the only think I would caution you about there is the `app.enable('trust proxy');` - that causes it to trust an unlimited number of `X-Forwarded-For` headers, which means a malicious actor can just add their own header with a random IP and get effectively unlimited use of your API.

Is this even possible if I don't have the header?

**Comment by Loom4k** [comment]
You could try switching to a different host (or your computer) in order to test again. Repl.it seems to have an integrated proxying system. Try this and come back if it doesn’t work! :)

**Comment by VeryHamburger** [comment]
I'll close this issue now because everything seems to work. Hopefully people won't be able to bypass.
