### ISSUE TITLE
Use same RateLimiter in different files

### ISSUE THREAD

**Issue by pgamerxdev** [nfriedly/express-rate-limit#248]
Hey there, I was wondering how I can use same limiter in different files. Because I make different limiter for Different files and that doesn't work really great because I feel like it's making different rate-limits for different endpoints in a same version

**Comment by nfriedly** [comment]
Sorry, this one slipped through the cracks. It depends on the store you're using - the default memory store does have different rate-limits for each instance created., but the other stores will all default to sharing their state between each other.

To use the default memory store with multiple files, create one file that just creates and exports a single instance of the ratelimiter, and then import that file and use that instance everywhere.

For example:

```js
const rateLimit = require("express-rate-limit");

const limiter = rateLimit({
  // ...
});

exports.getLimiter = () => limiter;
```

Then call `getLimiter()` wherever you need it in your app to ensure you're using the same instance everywhere.

**Comment by pgamerxdev** [comment]
Thank you a lot
