### ISSUE TITLE
Can i change ban time?

### ISSUE THREAD

**Issue by GorlikItsMe** [nfriedly/express-rate-limit#250]
For example if someone send 100 requests in 1minute i want block him for 10 minutes not for 1 minute. Can i do this using this library?

I see https://github.com/nfriedly/express-rate-limit/issues/235
but from what I understood it was about limiting or not limiting specific users.

I just want make longer ban time

**Comment by YaakovR** [comment]
@GorlikItsMe I see that marked this issue as completed. How do you change the ban time?

**Comment by nfriedly** [comment]
That's not a feature of this library. I believe you could do it with [rate-limiter-flexible](https://www.npmjs.com/package/rate-limiter-flexible) using the [blockDuration](https://github.com/animir/node-rate-limiter-flexible/wiki/Options#blockduration) option.
