### ISSUE TITLE
Hi, I have a question express rate and express-slow-down shared the same store when using redis?

### ISSUE THREAD

**Issue by jensysantana** [nfriedly/express-rate-limit#253]
I using express rate limit and express-slow-down with the redis store.

so when i go to redis i only can see 
<img width="1232" alt="Screen Shot 2021-09-22 at 10 33 18 PM" src="https://user-images.githubusercontent.com/36571423/134447235-a2494402-2433-451e-906c-2915f6fd3077.png">

**Comment by nfriedly** [comment]
That looks like there,s a reverse proxy inbetween your app and the internet. try the trust-proxy setting:

```js
app.set('trust proxy', 1);
```
 see https://expressjs.com/en/guide/behind-proxies.html

**Comment by jensysantana** [comment]
yes, i have this line of code. thank you.

**Comment by nfriedly** [comment]
> so what do you want to know?

That it's working for you and I don't have to think about it again 🤣 

But, if you post what reverse proxy/proxies you're using and what their configurations are, I might be able to help.
