### ISSUE TITLE
Setting a Title for Rate-limit

### ISSUE THREAD

**Issue by VeryHamburger** [nfriedly/express-rate-limit#255]
Is it possible to set a title when you get rate-limited?

**Example:**
![EXQmjVgq1I](https://user-images.githubusercontent.com/72227790/136243225-57b12055-6df6-497f-8283-ba9dd4f503de.png)

**Comment by nfriedly** [comment]
Yes, just set the `message` setting to a string of HTML with a title, or, if you want to use a template or something like that, set the `handler` setting to a function that sends HTML.

**Comment by nfriedly** [comment]
No, but you can do a custom handler that checks the headers or a query pram or whatever and then decides based on that whether to send HTML or JSON

**Comment by nfriedly** [comment]
Take a look at https://expressjs.com/en/4x/api.html#res.format - that makes it easy to send JSON responses to API clients (based on the headers they set) and HTML to web browsers.
