### ISSUE TITLE
How to get remaining request of given IP / apiKey ?

### ISSUE THREAD

**Issue by thanhnguyennguyen** [nfriedly/express-rate-limit#261]

**Comment by nfriedly** [comment]
It's added to the `req` object as `req.rateLimit.remaining`, so you can get it while handling the request. 

There's not an API to get the remaining count for an arbitrary IP / key outside of a request's context, but if you're using an external store then I suppose you could query the store directly.

**Comment by thanhnguyennguyen** [comment]
I'm using RedisStore (https://www.npmjs.com/package/rate-limit-redis) but I don't the key to query it

**Comment by nfriedly** [comment]
Ok, for that one, it looks like the key is `rl:<key>` where `key>` is the IP address unless you have a custom key generator. 

See https://github.com/wyattjoh/rate-limit-redis/blob/660946a26653395579741a7cb16bb74d76679fa0/lib/redis-store.js#L8 and https://github.com/wyattjoh/rate-limit-redis/blob/660946a26653395579741a7cb16bb74d76679fa0/lib/redis-store.js#L44
