### ISSUE TITLE
does keyGenerator support async ?

### ISSUE THREAD

**Issue by thanhnguyennguyen** [nfriedly/express-rate-limit#265]
we need async for this to validate apiKey 

```
  keyGenerator: async (req, res) => {
    // uses api_key from querystring if present, fall back to ip otherwise
    const ffHeaderValue = req.header('x-forwarded-for') ? req.header('x-forwarded-for').split(',')[0] : ''
    const ip = ffHeaderValue || req.connection.remoteAddress

    if (!req.query.api_key) {
      return ip
    }
    let rate = await rateLimitController.getSubscriptionByApiKey(req.query.api_key)
    if (!rate) {
      return ip
    }
    return req.query.api_key
  },
```

**Comment by thanhnguyennguyen** [comment]
we need async for this to validate apiKey 

```
  keyGenerator: async (req, res) => {
    // uses api_key from querystring if present, fall back to ip otherwise
    const ffHeaderValue = req.header('x-forwarded-for') ? req.header('x-forwarded-for').split(',')[0] : ''
    const ip = ffHeaderValue || req.connection.remoteAddress

    if (!req.query.api_key) {
      return ip
    }
    let rate = await rateLimitController.getSubscriptionByApiKey(req.query.api_key)
    if (!rate) {
      return ip
    }
    return req.query.api_key
  },
```

**Comment by nfriedly** [comment]
I suppose that's possible, although it seems like you're mixing up responsibilities a bit here. It might be better to validate the API key and a separate piece of middleware before or after the rate-limiter.

Also, for what it's worth, the `max` function can be async. So if they don't supply a valid API key, you can just set a low limit there.

But, really, the validation should be somewhere else.

**Comment by thanhnguyennguyen** [comment]
i think the validation should be here. Because, the library use return value (ip or apiKey) of this one to save into dataStore (memoryStore or RedisStore)

**Comment by nfriedly** [comment]
I was thinking you could do the validation before request-rate-limit, and set something like `req.apiKey` if it's valid. Then the `keyGenerator` can be as simple as `(req) => req.apiKey || req.ip`.

🤷

**Comment by gamemaker1** [comment]
As of version [6.0.0](https://github.com/nfriedly/express-rate-limit/releases/tag/v6.0.0), `keyGenerator` can now be an async function: https://github.com/nfriedly/express-rate-limit/blob/master/source/lib.ts#L225
