### ISSUE TITLE
'express-rate-limit' does not provide an export named 'default' when running with jest with --experimental-vm-modules

### ISSUE THREAD

**Issue by soruly** [nfriedly/express-rate-limit#267]
### Description

```
$ npm run jest

> trace.moe-api@1.0.0 jest
> NODE_NO_WARNINGS=1 NODE_OPTIONS=--experimental-vm-modules jest --runInBand

Determining test suites to run...
 FAIL  src/get-status.test.js
  ● Test suite failed to run

    SyntaxError: The requested module 'express-rate-limit' does not provide an export named 'default'

      at Runtime.linkAndEvaluateModule (node_modules/jest-runtime/build/index.js:779:5)
```

This has been working for express-rate-limit@5.5.1 with nodejs and jest, and working with 6.0.0 with nodejs, but not with jest

Maybe jest (27.4.5) doesn't fully support ESM yet. Running with node is perfectly fine.

This test are written in ESM and requires `--experimental-vm-modules` to run with jest, because it doesn't transpile anything with babel.

The test case: https://github.com/soruly/trace.moe-api/blob/master/src/app.js

### Library version

6.0.0

### Node version

v16.13.0

### Module system

ESM

**Comment by gamemaker1** [comment]
Hi @soruly,

This is [a known issue](https://github.com/facebook/jest/issues/9771) with Jest (it does not support the `exports` field in `package.json`). A similar issue exists on the Jest repo - https://github.com/facebook/jest/issues/11742).

There is [a PR to fix it](https://github.com/facebook/jest/pull/11961) that [might be part of Jest v28](https://github.com/facebook/jest/pull/11961#discussion_r758162104), but until then you can use the workaround described [here](https://github.com/facebook/jest/pull/11961#discussion_r748903736) (basically, just delete the `main` field from `node_modules/express-rate-limit/package.json` before running the test and restore it after).

Hope this helps.

**Comment by soruly** [comment]
Thanks, I'll stay in old version until then ;)

**Comment by gamemaker1** [comment]
Hi @soruly,

Could you try running these tests again with v6.0.1 - they seem to run fine in [this example project](https://github.com/gamemaker1/test/tree/express-rate-limit-hotfix/repro/ts-esm).

Thanks!

**Comment by soruly** [comment]
Hi @gamemaker1

Confirmed working with v6.0.1 without any modifications, thanks :D
