### ISSUE TITLE
How to import this into Typescript

### ISSUE THREAD

**Issue by krishnaTORQUE** [nfriedly/express-rate-limit#268]
### Description

How to import this into typescript?

None of those below working

`import rateLimit from express-rate-limit''`

`const rateLimit = require('express-rate-limit')`

`const rateLimit = (await import('express-rate-limit')).default`

### Library version

6.0.0

### Node version

16.13.1

### Typescript version (if you are using it)

4.5.4

### Module system

CommonJS

**Comment by gamemaker1** [comment]
Hi @krishnaTORQUE,

Could you please share the error you are getting when you compile the code? (run `npx tsc`)

The following should work while using the library with Typescript:

```
import rateLimit from 'express-rate-limit'
```

**Comment by krishnaTORQUE** [comment]
`Error [ERR_REQUIRE_ESM]: require() of ES Module`

**Comment by gamemaker1** [comment]
Could you try the following instead:

```ts
const rateLimit = require('express-rate-limit/dist/cjs/index.js')

// OR

import rateLimit from 'express-rate-limit/dist/cjs/index.js'
```

**Comment by gamemaker1** [comment]
Also, could you please paste your `tsconfig.json`?

**Comment by krishnaTORQUE** [comment]
```json
{
  "extends": "ts-node/node16/tsconfig.json",
  "ts-node": {
    "transpileOnly": false,
    "files": true,
    "compilerOptions": {
      "module": "commonjs"
    }
  },
  "compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": ["esnext"],
    "jsx": "react",
    "moduleResolution": "node",
    "allowJs": true,
    "checkJs": true,
    "noImplicitAny": true,
    "noImplicitReturns": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "removeComments": true,
    "strict": true,
    "noFallthroughCasesInSwitch": true,
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "importHelpers": true,
    "outDir": "buildServer",
    "rootDirs": ["src"]
  },
  "exclude": ["node_modules"]
}

```

**Comment by krishnaTORQUE** [comment]
> Could you please try the following instead:
> 
> ```ts
> const rateLimit = require('express-rate-limit/dist/cjs/index.js')
> 
> // OR
> 
> import rateLimit from 'express-rate-limit/dist/cjs/index.js'
> ```

Tried but still error
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/esm/index.js' is not defined by "exports" in`

**Comment by gamemaker1** [comment]
I think the problem is node treats even the CJS files in the `dist/cjs/index.js` as ESM files because the root `package.json` has `type: module` in it.

**Comment by krishnaTORQUE** [comment]
For `cjs` is the same error

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/cjs/index.js' is not defined by "exports" in`

I am not using type:module in the app packages json but express rate limit does use type:module

**Comment by gamemaker1** [comment]
Yes, I think the latest version has introduced a bug which does not allow it to work with CJS projects. Could you please use version `5.5.1` (`npm install express-rate-limit@5.5.1`) until we fix this?

**Comment by krishnaTORQUE** [comment]
Yes sure

**Comment by gamemaker1** [comment]
Hi @krishnaTORQUE,

Could you please try hotfix out:

```
npm install https://raw.githubusercontent.com/gamemaker1/test/express-rate-limit-hotfix/assets/express-rate-limit-6.0.0.tgz
```

Then:

```ts
import rateLimit from 'express-rate-limit'
```

I tested it with this minimal project [here](https://github.com/gamemaker1/test/tree/express-rate-limit-hotfix/repro).

Thanks for your patience!

**Comment by krishnaTORQUE** [comment]
> Hi @krishnaTORQUE,
> 
> Could you please try hotfix out:
> 
> ```
> npm install https://raw.githubusercontent.com/gamemaker1/test/express-rate-limit-hotfix/assets/express-rate-limit-6.0.0.tgz
> ```
> 
> Then:
> 
> ```ts
> import rateLimit from 'express-rate-limit'
> ```
> 
> I tested it with this minimal project [here](https://github.com/gamemaker1/test/tree/express-rate-limit-hotfix/repro).
> 
> Thanks for your patience!

Hi
Looks like its working fine.

**Comment by gamemaker1** [comment]
That's great, I'll release a patch version 6.0.1 with this fix soon.

@nfriedly I had to add another package.json with the `dist/cjs` and `dist/esm` built files. This is so that the `dist/cjs` code is considered a CommonJS module and `dist/esm` code is considered an ESM module.

**Comment by nfriedly** [comment]
Oof, I'm sorry I missed that everyone :(

Thank you @gamemaker1 for getting a fix shipped so quickly! 

I ought to add a test for this scenario. (But I think you made the right call in just shipping the fix right away.)
