### ISSUE TITLE
CommonJS / TypeError: rateLimit is not a function

### ISSUE THREAD

**Issue by cloudflips32** [nfriedly/express-rate-limit#273]
### Description

on index.js
```
1 const rateLimit = require('express-rate-limit')

12 // Rate Limit
13 const limiter = rateLimit({
14 windowMs: 10*60*1000,
15 max: 100
})
17 app.use(limiter)
18 app.set('trust proxy', 1)
```
after npm run dev, terminal reads
TypeError: rateLimit is not a function
    at Object.<anonymous> (index.js:12:17)

Please advise. Thank you.

### Library version

^6.0.1

### Node version

16.13.0

### Module system

CommonJS

**Comment by cloudflips32** [comment]
Revised top module and works per Github readme. Please advise a change to npm docs in usage section to reflect this CJS statement

const rateLimit = require('express-rate-limit')==.default==

 Have a good New Years!

**Comment by nfriedly** [comment]
Sorry, the `.default` thing is a temporary fix; we're working on a point release that should resolvethe underlying issue and remove the need for it in #272

**Comment by gamemaker1** [comment]
Pinning for more visibility until #272 is merged

**Comment by gamemaker1** [comment]
Hi @cloudflips32,

We just released v6.0.2, could you please try it out:

```
npm install express-rate-limit@6.0.2
```

```js
const rateLimit = require('express-rate-limit')
```

and let us know if this fixes the problem?

Thanks!

**Comment by cloudflips32** [comment]
Reads 200 in production and deploy!

Have a good New Years!

**Comment by gamemaker1** [comment]
Glad to hear that!

> Have a good New Years!

You too <3
