### ISSUE TITLE
RateLimit is not a constructor

### ISSUE THREAD

**Issue by Fazil-vk** [nfriedly/express-rate-limit#286]
### Description

```ts
var limiter = new rateLimit({
............................^
TypeError: rateLimit is not a constructor
```

how to fix this?

### Library version

^6.1.0

### Node version

v14.16.0

### Module system

CommonJS

**Comment by gamemaker1** [comment]
The exported `rateLimit` is a function, not a class. You can fix the problem by removing the `new` before `rateLimit({ ... })`

**Comment by Fazil-vk** [comment]
> The exported `rateLimit` is a function, not a class. You can fix the problem by removing the `new` before `rateLimit({ ... })`.

Ok bro, thanks

**Comment by nfriedly** [comment]
This might be my fault. A while back, the examples in the readme all had `new` - it wasn't needed then, but it didn't used to throw errors. Anyways, glad to hear it's working for you now :)
