### ISSUE TITLE
Global Ratelimits

### ISSUE THREAD

**Issue by callumisdumb** [nfriedly/express-rate-limit#301]
### Description

For some reason, ratelimits using this package are global, therefore leading to my entire user base being affected by 1 person being ratelimited. I've also had fellow friends and coworkers experience this issue on personal and other work-related projects.

### Library version

^6.2.0

### Node version

v16.14.2

### Module system

CommonJS

**Comment by kvyuaiss** [comment]
This is so true! I can't stand those global rate-limits limiting all of my users to my platform!

So annoying.

**Comment by realgavinmartin** [comment]
I'm having this issue on api.campfirehq.net, strange.

**Comment by kvyuaiss** [comment]
> I'm having this issue on api.campfirehq.net, strange.

Wow! I am too. Maybe someone DDosed and then express-rate-limits did a bad job and blocked everyone!

**Comment by nfriedly** [comment]
That's kind of weird that this broke a bunch of people all at once. Can you each tell me what hosting provider you're on, what your `trust proxy` setting is (if any), and if you're behind any kind of load balancer or reverse proxy or anything along those lines?

**Comment by callumisdumb** [comment]
> That's kind of weird that this broke a bunch of people all at once. Can you each tell me what hosting provider you're on, what your `trust proxy` setting is (if any), and if your node.js server is behind any kind of load balancer or reverse proxy or anything along those lines?

I believe this is a sort of isolated incident to DigitalOcean, as personally I run my API off a DigitalOcean server which caused an issue. As far as I'm aware api.campfirehq.net runs off a DigitalOcean droplet however I'm not able to give you any sort of information regarding that server as its not mine, I just used to know the owner of campfirehq.net.

The server doesn't have a trust proxy and is not behind a load balancer or reverse proxy, however I do believe the issue is the package actually blocking the server itself. Not too sure what the issue could be, its a strange one indeed.

**Comment by nfriedly** [comment]
Another request, if you can deploy changes easily, can you write an endpoint that returns `req.ip` and `req.headers` when you make a request, and then give me that output + your actual IP?

Something like 

```js
app.get('/test', (req,res) => res.send({ip: req.ip, headers: req.headers}));
```

And then give me that response + whatever whatsmyip.com reports?

**Comment by nfriedly** [comment]
It's getting pretty late here, so I'm not going to be online much longer this evening. I will say that typically when this symptom occurs, the issue is that there _is_ something like a load balancer or reverse proxy in between the server and the internet, and setting an appropriate `trust proxy` value resolves the issue. 

You can try `app.set('trust proxy', true)` just to test it and see if that fixes it, but that actually leaves a bit of a security hole open, so you want to switch it to a number, such as `app.set('trust proxy', 1)` - just use the lowest number that works (usually `1`) to prevent the security hole.

**Comment by realgavinmartin** [comment]
Seems to be working fine now with the trust proxy

**Comment by nfriedly** [comment]
Cool, I'm going to go ahead and close this then. 

Cheers!
