### ISSUE TITLE
Get headers in handler

### ISSUE THREAD

**Issue by codergautam** [nfriedly/express-rate-limit#308]
### Description

Basically, in the handler function, you should be able to get the headers for example `X-RateLimit-Remaining`.

### Why

I'm trying to make the rate limit message display how long till you can try again, but doing req.get("X-RateLimit-Remaining") returns undefined.

### Alternatives

None currently (as far as I know)

**Comment by codergautam** [comment]
I spoke too soon-

I was able to get the headers by using `res.getHeaders()`

Sorry about that!

**Comment by nfriedly** [comment]
Yep, that works. There is also a `req.rateLimit` object added to the request - see https://github.com/nfriedly/express-rate-limit#request-api
