### ISSUE TITLE
503 Error after about 6 hours uptime on heroku

### ISSUE THREAD

**Issue by StevePavlin** [nfriedly/express-rate-limit#31]
This is only happening to my endpoints using this module. Here is my config:

```
 var limiter = new RateLimit({
      store: new RedisStore({
        client: redis(config.get('redisUrl'))
      }),
      handler: function (req, res /*next*/) {
        res.json({error: 'Too many recent requests.'})
      }
    });


    app.post(baseURL + '/test', limiter, function (req, res) {
       res.json({});
    });
```

After about 5 hours of uptime, these endpoints stop responding:
```Uncaught Response with status: 503 OK for URL: http://127.0.0.1/api/v1/test```

Any idea why? Is it the redis module?

**Comment by nfriedly** [comment]
Hi Steve, that's strange. Especially the combination of `503 Service Unavailable` status code and `200 OK` status text. I don't think I've ever seen that anywhere.

Is this a free heroku server - if so, could it be related to [sleeping](https://devcenter.heroku.com/articles/free-dyno-hours)?

If not, I'm honestly not sure. It is possible that the error is coming from the redis server and propagating all the way back.

**Comment by StevePavlin** [comment]
My guess after some testing is the fact that I was letting the module fall back to IP key generation and I was behind heroku + cloudflare which allowed for only a few unique IP's to be accessing the app. I will report my findings in a similar production environment with using my passport session user id as my key generator.
