### ISSUE TITLE
ESM monorepo fails to find types declaration

### ISSUE THREAD

**Issue by rafaelpimpa** [nfriedly/express-rate-limit#319]
### Description

Somehow Typescript can't find the type declarations when using ``type: module`` in package.json

When I remove ``type: module``, it works fine.

```js
// tsconfig.json
{
  "compilerOptions": {
    "target": "ESNext",
    "module": "Node16",
    "moduleResolution":"Node16",
    "outDir": "./dist",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "skipLibCheck": true,
    "rootDir": "./src",
    "baseUrl": ".",
    "paths": {
      "#api/*": ["./src/*"]
    }
  },
  "include": ["src/**/*.ts", "src/**/*.d.ts"],
}
```

Importing like:
```js
import rateLimit from 'express-rate-limit'
```
Got the error:
```
Could not find a declaration file for module 'express-rate-limit'. 'C:/projects/x/node_modules/.pnpm/express-rate-limit@6.5.1_express@4.18.1/node_modules/express-rate-limit/dist/index.mjs' implicitly has an 'any' type.
  Try `npm i --save-dev @types/express-rate-limit` if it exists or add a new declaration (.d.ts) file containing `declare module 'express-rate-limit';`ts(7016)
```

What am I doing wrong?

### pnpm version

7.9.3

### Library version

6.5.1

### Node version

16.15.0

### Typescript version (if you are using it)

4.7.4

### Module system

ESM

**Comment by gamemaker1** [comment]
Is that a VSCode error, or a TSC error? Sometimes you need to reload VSCode so it recognises a package's types.

**Comment by rafaelpimpa** [comment]
@gamemaker1 it compiles but I do get the error in terminal as well. Yes I've restarted TS server and VScode itself, nothing changes.

**Comment by gamemaker1** [comment]
I couldn't reproduce this issue locally, could you please try deleting `node_modules/` and try re-installing them?

**Comment by rafaelpimpa** [comment]
Also this problem is not exclusive to pnpm, it has the same problem with yarn v1, and npm v8, both with ``workspace`` settings.
