### ISSUE TITLE
Memory leak with jest and supertest

### ISSUE THREAD

**Issue by codyebberson** [nfriedly/express-rate-limit#320]
### Description

Hello, thanks for this fantastic library.

We use `express-rate-limit` in our app, and noticed that it is the source of memory leaks when testing with [jest](https://jestjs.io/) and [supertest](https://github.com/visionmedia/supertest).

Here is a minimal reproducing repo: https://github.com/codyebberson/rate-limit-memory-leak-demo

server.js:

```js
const express = require("express");
const rateLimit = require("express-rate-limit");

function setupApp() {
  const app = express();

  app.use(rateLimit({
    windowMs: 15 * 60 * 1000, // 15 minutes
    max: 10, // Limit each IP to 100 requests per `window` (here, per 15 minutes)
  }));

  app.get("/", (req, res) => res.send("Hello World!"));

  return app;
}

if (require.main === module) {
  setupApp().listen(8000, () => console.log("Listening to Port 8000"));
}

module.exports = setupApp;
```

server.test.js:

```js
const request = require("supertest");
const setupApp = require("./server");

test("memory leak", async () => {
  const app = setupApp();
  const res = await request(app).get("/");
  expect(res.status).toBe(200);
});
```

When run with jest's `--detectLeaks`:

```
npm t -- --detectLeaks

> rate-limit-memory-leak-demo@0.0.0 test
> jest "--detectLeaks"

FAIL ./server.test.js
  ● Test suite failed to run

    EXPERIMENTAL FEATURE!
    Your test suite is leaking memory. Please ensure all references are cleaned.

    There is a number of things that can leak memory:
      - Async operations that have not finished (e.g. fs.readFile).
      - Timers not properly mocked (e.g. setInterval, setTimeout).
      - Keeping references to the global scope.

      at onResult (node_modules/@jest/core/build/TestScheduler.js:188:18)
      at node_modules/@jest/core/build/TestScheduler.js:300:17
      at node_modules/emittery/index.js:311:13
          at Array.map (<anonymous>)
      at Emittery.emit (node_modules/emittery/index.js:309:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.787 s, estimated 1 s
Ran all test suites.
```

I believe the source of the leak is the interval from `setInterval` in [`MemoryStore`](https://github.com/nfriedly/express-rate-limit/blob/master/source/memory-store.ts).  I verified that `interval.unref()` is being called, but the memory leak persisted.

We were able to work around it by creating a [custom `MemoryStore`](https://github.com/medplum/medplum/pull/872/files#diff-b1af84d2560bf263c698b5e3a5a470f8bb87e49757fa39c52f0d20583a468db5R54-R104) that adds a `shutdown` method, which calls `clearInterval` on the interval handle.

If you are open to it, I would be happy to submit a PR with a similar fix.

### Library version

6.5.1

### Node version

18.2.0

### Module system

CommonJS

**Comment by nfriedly** [comment]
From the error message:

> - Timers not properly mocked (e.g. setInterval, setTimeout).

Did you try enabling fake timers? - https://jestjs.io/docs/timer-mocks

That's what we do for the tests in this library: https://github.com/nfriedly/express-rate-limit/blob/12deb5cc3d77710b4bc7fe36bf4ac439cb5d43da/test/library/memory-store-test.ts#L9-L16

I just tested it with `npx jest --detectLeaks test/library/memory-store-test.ts` and it did not report any memory leaks.

I'm not *completely* against adding a `shutdown` method, but I don't think it's needed in this case. Please try mocking the timers first. (Mocking timers in tests is a good idea in general because, in addition to preventing this type of memory leak, it can also make your tests faster and more reliable.)

**Comment by codyebberson** [comment]
Hi @nfriedly thanks for the response.

Fake timers are a perfectly valid suggestion.  They didn't work in our case, because they interfere with other 3rd party dependencies, but I agree with the suggestion in principle.

Feel free to close this out.  Thanks for looking.

**Comment by nfriedly** [comment]
Ok, why don't you go ahead and send a PR with the `shutdown` method.
