### ISSUE TITLE
skipFailedRequests Behavior / 429 responses not counting against limits

### ISSUE THREAD

**Issue by gmillerd** [nfriedly/express-rate-limit#325]
### Description

Hello, How do I include 429 responses of a requester against their quota / limit? Right now, out of the box, if someone is "persistently overzealous", they are just unlocked at the next window expiration comes about. For some requesters, this just means ... retry more.

When I read the wording of  the option "skipFailedRequests" it seems like it would do exactly this, but it doesn't seem to do so.

Example: With this config (larger values don't seem to matter) a small command hits the limit ... keeps on on requesting and then is allowed back. 

Thank you

```
app.use(rateLimit({
    windowMs: 10 * 1000,
    max: 10,
}));
```

various lines omitted for visibility

```
$ while true; do curl -s -I http://localhost:3000/test | grep -E '(^HTTP|X-RateLimit-)'; done
HTTP/1.1 200 OK
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 9
X-RateLimit-Reset: 1663059180
HTTP/1.1 200 OK
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 8
X-RateLimit-Reset: 1663059180
...
HTTP/1.1 200 OK
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1663059180
HTTP/1.1 429 Too Many Requests
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1663059180
...
HTTP/1.1 429 Too Many Requests
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 0
X-RateLimit-Reset: 1663059180
HTTP/1.1 200 OK
X-RateLimit-Limit: 10
X-RateLimit-Remaining: 9
X-RateLimit-Reset: 1663059190
```

### Library version

6.6.0

### Node version

18.8.0

### Module system

CommonJS

**Comment by nfriedly** [comment]
429's do count against the quota by default, the `skipFailedRequests` option reverses that behavior and makes 429's not count (however, the user is already rate-limited at that point - the option is mainly intended for other 4xx/5xx responses.)

The thing you're running into is that the quota is eventually reset regardless of whether or not the user keeps sending requests. This is default behavior for all of the stores, and it's the only option with the default MemoryStore.

However, if you want to continue blocking until the user stops sending requests, you can use a different store that supports that - I know the [redis](https://www.npmjs.com/package/rate-limit-redis) and [mongo](https://www.npmjs.com/package/rate-limit-mongo) both have an option to reset the expiration date on change (meaning every request pushes it back farther). 

I'm not sure if the other stores support that feature, but it should be possible to add in some cases. The default store, however, is optimized for less overhead and is not going to support that feature.

**Comment by gmillerd** [comment]
Thank you for the quick and detailed explanation.
