### ISSUE TITLE
Request: more options when limit is reached

### ISSUE THREAD

**Issue by jerome724** [nfriedly/express-rate-limit#36]
Hey!

rate-limit is working 10/10, but i would like to have a bit more options when someone reaches the limit, instead of displaying a plain message maybe rendering another file or responding with an JSON obj. like 

```json
{
"429": "Too Many Requests"
}
```

or something like this. 

~ Jerome
- can i add a label to this "issue"?

**Comment by nfriedly** [comment]
Hi @jerome724,

Try setting the `handler` option to a custom function - see https://github.com/nfriedly/express-rate-limit#configuration for an example.

**Comment by jerome724** [comment]
Woops yeah... sorry, should have read the docs with more effort 👎 Thanks for the Middleware!
