### ISSUE TITLE
Distinguish between initial and others rate-limit attempts

### ISSUE THREAD

**Issue by cguedes** [nfriedly/express-rate-limit#38]
I need to know/distinguish between the first attempt outside the rate limit (`current == options.max + 1`) and the others (`current > options.max + 1`).

I see two options:

a) provide `current` and `options` to the `handler` function
b) create a new method (ex: `limit`) that will be called on the first attempt outside the rate limit

CC @mderazon

**Comment by nfriedly** [comment]
This will take some reworking but, like I mentioned on the other ticket, I was already thinking of possibly reworking things for a new major version.

I think the Store API will need to be updated to return more data from the `incr` method. As with the other one, I'm not sure when I can get to this, but I'll try and bump up the priority.

**Comment by nfriedly** [comment]
As of v3.0.0 the `onLimitReached` callback will only be triggered once per window
