### ISSUE TITLE
Use option `delayMs` in 429 responses

### ISSUE THREAD

**Issue by cguedes** [nfriedly/express-rate-limit#39]
In [line 73](https://github.com/nfriedly/express-rate-limit/blob/53f858c6536dd07d1df61da0f2022dd053c68e04/lib/express-rate-limit.js#L73) we can see that the `handler` func is being called without using the `delayMs` (used in [line 78](https://github.com/nfriedly/express-rate-limit/blob/53f858c6536dd07d1df61da0f2022dd053c68e04/lib/express-rate-limit.js#L78)).

I think that the `handler` should also be delayed.

CC @mderazon

**Comment by nfriedly** [comment]
Hum, that's interesting. I have a plan of spinning that part off into a separate module, so express-rate-limit would just allow or block, and then the new one, express-slow-down (or whatever) would get the response delaying behavior. Once that's done, you're be able to achieve your desired behavior by making both work on the same endpoint with the slow-down one handling requests first. (Or the current behavior if slow-down was used second.)

I'm not sure when I'll get to this, but I can try and prioritize it a bit if it's a need for you.

**Comment by nfriedly** [comment]
This is now complete: use https://github.com/nfriedly/express-slow-down first and then express-rate-limit and the 429 responses will be delayed
