### ISSUE TITLE
Implement a reset function

### ISSUE THREAD

**Issue by germanattanasio** [nfriedly/express-rate-limit#4]
Can you please add  a `reset(req, res, next)` function for when we want to reset specific IPs.
I use your work to create [this](https://github.com/watson-developer-cloud/personality-insights-nodejs/blob/livedemo/config/rate-limit.js) but it will be great if I was able to use your library.

Take into account that in order to implement the `reset` functionality you now need to somehow save the `setTimeout()` and call `clearTimeout()`

**Comment by nfriedly** [comment]
Yea, although I'm thinking that it probably shouldn't be middleware (and a breaking api change) -  what if the new api looked like this:

```js
var RateLimit = require('express-rate-limit');
var limiter = RateLimit({/*...*/});

app.use('/api/', limiter); // limit some endpoints

// reset endpoint - not rate-limited, at least not with the same limiter...
app.post('/reset-rate-limit', function(req, res) {
   // validate that req has filled out a captcha properly or whatever and then...
  limiter.reset(req.ip); // or perhaps just limiter.reset(req); ? 
```

Then we could take your captcha code and put that into a new module built on top of this one to get it out of the sample app.

**Comment by germanattanasio** [comment]
Looks good. I will write the google captcha module on top of this

**Comment by nfriedly** [comment]
Cool then, I can have this implemented fairly quickly.

**Comment by nfriedly** [comment]
I switched it to a global `setInterval` instead of individual `setTimeouts` for each request, which made the reset api a lot easier to add. It mostly behaves the same, but the change was significant enough that I decided to bump it to v2.
