### ISSUE TITLE
How long can I store max amount in the memory for?

### ISSUE THREAD

**Issue by mihirchronicles** [nfriedly/express-rate-limit#42]
I have a max setup to 10 but then it expires after an hour. I am using req.ip == to 127.0.0.1  to keep track of keyGenerator. 

How can I fix this so it doesn't go over max after certain period of time?

**Comment by mihirchronicles** [comment]
And what is the max I can store the state of the max in memory?

**Comment by nfriedly** [comment]
Set `options.windowMs` to a higher value. 

They're both numbers, so there's no real max, but you probably want to stick to something shorter like `24*60*60*1000` (24 hours) for `windowMs` and no more than 9007199254740991 (`Number.MAX_SAFE_INTEGER`) for `max`.
