### ISSUE TITLE
V3 Goals

### ISSUE THREAD

**Issue by nfriedly** [nfriedly/express-rate-limit#46]
Goals for v3:

* [x] Move the delay options to a new module that only slows down repeat requests - call it  `express-rate-limit-slow-down` or something like that
  * DONE - see https://github.com/nfriedly/express-slow-down
* [x] Add `X-RateLimit-Reset` header - #32 - has issues with using an external store. Possible solutions:
  * Only enable the header when the store provides some particular flag/method/value indicating support
    - And then submit a (backwards-compatible) PR to known stores
* [ ] Consider removing some of the other options in order to further simplify things.
* [x] Don't automatically switch formats depending on the request headers. Instead just use `req.send(options.message)` 
  - express automatically stringifies objects to json and sets the appropriate application/json content-type. #53
* [x] Make `onLimitReached` only fire once before an IP resets - #64, #38

**Comment by nickzuber** [comment]
For v3 should we consider deprecating headers named `X-...` and effectively remove the `X` from all the custom header names? It's the convention now: 

> SHOULD NOT prefix their parameter names with "X-" or similar constructs.

[RFC 6648](https://tools.ietf.org/html/rfc6648)

Not a major issue or anything but if you're gonna upgrade to a new major version this could be something easy to add.

**Comment by nfriedly** [comment]
That's interesting, I didn't know about the change in convention.

However that won't be part of an SDK change, it's a service level feature. The convention in the SDK has generally been to use whatever name the service uses, but you do have a fair point that this is awkward with X-... headers.

**Comment by tjallingt** [comment]
What is the status on this?
Especially the first point is of interest to me as i find it strange that the default behaviour of this middleware is to start delaying requests by one second after the first request, which I don't think is a common usecase for most users of a rate limit middleware 😕

**Comment by nfriedly** [comment]
Hey,

Things are kind of in maintenance mode right now. I changed jobs so I can no longer work on this during working hours, and I don't have a lot of time available outside of work.

I know a lot of people use this, so I basically accept most PRs that don't break backwards compatibility. Even for a v3 release, where it's OK to remove or break some features, I'd still like to keep compatibility with the existing stores that people have written.

If you're interested and available, I'd love some support with creating a v3 that made a little more sense. It wouldn't have to hit all of the above points, anything would be progress.

I just reworded the ticket to make a little more sense and remove the idea of dropping support for external stores - that wouldn't be a good idea at this point.

**Comment by tjallingt** [comment]
Hey @nfriedly thanks for the quick reply, don't worry i understand you are bussy 😄 

I might drop a quick pr for a start on v3 but I will mostly focus on removing complexity that I don't think is necessairy (such as the delay stuff)

When that is out we can start looking ahead at how to re-implement lacking functionality in ways that make the most sense.

**Comment by ashraful-islam** [comment]
@nfriedly 

- [ ] Make `onLimitReached` only fire once before an IP resets

That is literally just one additional `if , may be set it for `first-timer-only` or something like that.

@tjallingt if you started the v3 branch, I could help with one or two checkboxes :)

**Comment by nfriedly** [comment]
It's done!
