### ISSUE TITLE
onDelayReached() ?

### ISSUE THREAD

**Issue by powmedia** [nfriedly/express-rate-limit#47]
Similar to how `onLimitReached()` is implemented, it would be great if there was an option such as `onDelayReached()` which would trigger when the request delay is started for an IP address.

**Comment by powmedia** [comment]
If this is something you'd be interested in I may be able to submit a PR

**Comment by nfriedly** [comment]
Hey, sorry I missed this ticket; I just moved the delay parts to a separate library, https://github.com/nfriedly/express-slow-down and there onDelayReached will trigger the first time a delay is started for a given time window.
