### ISSUE TITLE
Run function on blobk IP

### ISSUE THREAD

**Issue by Thinkdiff** [nfriedly/express-rate-limit#50]
I'm using this package. When an IP address has reached the limitation, the system will show an error message that I've set. But I need, when somebody has reached the limitation, a system run a function about that IP. How can I do that?

I mean I`m using "onLimitReached" but now I have a new problem. I wrote a function that when an IP has reached the limitation, the system will block this IP in the firewall. The problem is, when system found an IP that reached the limitation, it blocks some 4 or 5 IP that is sending request after bad IP.

for example, this is the capture of 5 seconds of requests:

1.1.1.1
2.2.2.2
3.3.3.3
4.4.4.4
5.5.5.5
6.6.6.6

And imagine "5.5.5.5" is a bad IP that reached the limitation. The system will block these IPs:
1.1.1.1
2.2.2.2
3.3.3.3
4.4.4.4
5.5.5.5

why??

**Comment by nfriedly** [comment]
I have no idea.. why are you blocking IPs in your firewall?

**Comment by nfriedly** [comment]
Hey, I'm trying to clean up old issues; did you ever work out what was happening here?
