### ISSUE TITLE
Block Request based on user params.

### ISSUE THREAD

**Issue by 23ranjan** [nfriedly/express-rate-limit#54]
Hi @nfriedly,

Is there any way to block a request per user instead of IP. For ex if I send user id in request headers and I want to block a request on the basis of user id so that all other users connecting from the same ip should not be blocked.

Thanks,
Ranjan

**Comment by nfriedly** [comment]
Yes, this is possible, set the keyGenerator function to one that pulls in the user ID (or whatever you want):

```js
var limiter = new RateLimit({
  keyGenerator:  function (req, res) {
    return req.headers['user-id'];
  }
});
```
