### ISSUE TITLE
apply express-rate-limit to dynamic routes

### ISSUE THREAD

**Issue by psimoesSsimoes** [nfriedly/express-rate-limit#55]
I would like to know if this the expected behavior of express-rate-limiter or if i'm not using express-rate limiter correctly.

i have some routes that are dynamically generated like so:

router.post('/foo/:x/:y', limiter,callback function)

If i access /foo/example1/example2 and /foo/example3/example4 it will count for the same limiter.
Is there a way where i can have a limiter for each different dynamically generated route?
The purpose is to have 1 limiter for /foo/example1/example2, another for /foo/example3/example4 and so on, and so on.

I'm using express4

Any help would be appreciated.

**Comment by nfriedly** [comment]
It might work the way you want if you define a custom key generator that takes the URL into account:

```js
var fooLimiter = new RateLimit({ 
  keyGenerator: function (req) {
    Return req.ip + req.url;
  }
 }); 

// only apply to requests that begin with /foo/
 app.use('/foo/', fooLimiter);
```

I'm writing this on my phone, so it might not be exactly right, but that should give you the general idea.

**Comment by psimoesSsimoes** [comment]
Ok, i got the idea. Thanks for your feedback
