### ISSUE TITLE
Rate limit decreasing faster than actual requests

### ISSUE THREAD

**Issue by mridah** [nfriedly/express-rate-limit#60]
I have an API hosted on [https://conv.mridulahuja.com/INR/0.5656](url). Now, when you make the first request, the response will have header `X-RateLimit-Remaining:19` which is correct. When I make the same request again, it shows say, `X-RateLimit-Remaining:15`, when it should be 18, and keeps on decreasing for example: 15 -> 11 -> 6 -> 0. As a result, it only allows 4-5 requests when I want to allow 20 requests per minute.

My code:

    var limiter = new RateLimit({
        windowMs: 1*60*1000,
        max: 20,
        delayMs: 0
    });
    app.use(limiter);

How to resolve this @nfriedly ??

**Comment by SimonSchick** [comment]
Are you testing this as the `/` route with a browser by chance? Might be favicon requests.

**Comment by eyelidlessness** [comment]
Could also be related to #69

**Comment by nfriedly** [comment]
Hey, I'm trying to clean up old issues; did you ever figure out the root of the issue?
