### ISSUE TITLE
Remove usage of `new` from docs.

### ISSUE THREAD

**Issue by SimonSchick** [nfriedly/express-rate-limit#62]
using the `new` operator suggests you are creating an instance of a class, this is not the case, you are instead returning a new closure, this can lead to a lot of confusion and is generally a very uncommon thing to do..

**Comment by nfriedly** [comment]
It *is* creating a new instance of a class (in the ES5 sense), it just an anonymous one because the constructor returns a function (to match the express API). But, I get your point - it isn't strictly necessary. Let me think about it a bit more.

**Comment by tjallingt** [comment]
express middleware convention is:

```javascript
app.use(myMiddleware(options));
```
http://expressjs.com/en/resources/middleware.html

so I agree with @SimonSchick  that the `new` operator  should not be used in the docs.

**Comment by nfriedly** [comment]
I went ahead and made this change for the 3.0 release.
