### ISSUE TITLE
`onLimitReached` is misleading

### ISSUE THREAD

**Issue by SimonSchick** [nfriedly/express-rate-limit#64]
The name suggests it's triggered when the limit is `reached`, not for every requests that is send after the limit is reached.

**Comment by nfriedly** [comment]
Hum, good point. As I mentioned on #63, this lib is due for a major revamping with a number of breaking changes, including something here.

**Comment by popkutty** [comment]
Created PR for this. @nfriedly can you please review and merge it, if you're ok with the changes.
https://github.com/nfriedly/express-rate-limit/pull/68

**Comment by nfriedly** [comment]
@SimonSchick See https://github.com/nfriedly/express-rate-limit/pull/68#issuecomment-358058305 for a way to trigger for just the request that first reaches the limit

**Comment by nfriedly** [comment]
As of v3.0.0 the onLimitReached callback will only be triggered once per window
