### ISSUE TITLE
How to show the remaining timeout?

### ISSUE THREAD

**Issue by subversivo58** [nfriedly/express-rate-limit#66]
I'm using custom HTML that shows the user the number of attempts and the waiting period but would like to show the time remaining until the user can actually use the route again.

```javascript

const getFile = filename => {
    return fs.readFileSync('./public/' + filename + '.html', 'utf-8')
}

const findAndReplace = (rule, replacement, model) => {
    model = model.replace(/{{+[a-zA-Z0-9_]+=+[a-zA-Z0-9_=:.\/@#&-]+}}/gi, wholeMatch => {
        if ( wholeMatch ) {
            wholeMatch = wholeMatch.replace(/{{/g, '').replace(/}}/g, '')
            let index = wholeMatch.split('=')
            //
            if ( Array.isArray(rule) ) {
                for (let i = 0; i < rule.length; i++) {
                     switch (index[0]) {
                         case rule[i]:
                             return replacement[i]
                         break
                     }
                }
            } else {
                switch (index[0]) {
                    case rule:
                        return replacement
                    break
                }
            }
        } else {
            return ''
        }
    })
    return model
}
const limiter = new RateLimit({
    windowMs: 30 * 60 * 1000,
    max: 3,
    delayMs: 0,
    message: findAndReplace(
        ['limit', 'expire', 'docs'],
        [3, 30, 'https://domain.com/documentation#limiter',
        getFile('limiter')
    )
})

// express route
route.get('/awesomeroute', limiter, (req, res, next) => {
    // do stuff....
})
```

The output would look something like this:

![limiter](https://user-images.githubusercontent.com/6475273/34321773-f5dd7f7e-e7fd-11e7-83b9-87aefa7dc7b6.PNG)

How could I get the remaining time to show the user instead of using the total time?

**Comment by gndplayground** [comment]
Well for GitHub API they have X-RateLimit-Reset: 1372700873 timestamps in the header. I think it is easy for us to mimic the Github API.

**Comment by gndplayground** [comment]
@nfriedly @subversivo58 I added the pull request https://github.com/nfriedly/express-rate-limit/pull/67

**Comment by subversivo58** [comment]
In my humble opinion I think this is useful for the library, there are n use cases where the application should treat user locking in a more refined way rather than simply informing that it is locked. Accompanying the PR [#67](https://github.com/nfriedly/express-rate-limit/pull/67)

**Comment by nfriedly** [comment]
As of v2.13, an X-RateLimit-Reset header is no provided when the MemoryStore is used. Other stores may be updated to provide the necessary value also.
