### ISSUE TITLE
Options request being included in rate limiting

### ISSUE THREAD

**Issue by ChrisCooney** [nfriedly/express-rate-limit#69]
Perhaps some built in detection for rate limiting options request? At the moment it will count it as one whole request despite it being a standard part of the CORS flow.

**Comment by ChrisCooney** [comment]
Worth noting that a good work around is to put this middlware before any CORS detection and not allow options requests to get through, but still might be a good addition.

**Comment by nfriedly** [comment]
Good point. In most cases, I wouldn't expect it to make that big of an impact, but if you're trying to enforce a really tight limit, then I suppose it would.

For a quick fix, you can do something like this:

```js
var limiter = new RateLimit({/* settings...*/});

// apply to whatever methods you actually care about
app.get('*', limiter);
app.post('*', limiter);
app.delete('*', limiter);
```

(I think that `'*'` works as a catch-all, try `/.*/` if not.)

**Comment by hellodavecooper** [comment]
I had a similar problem. Using the `skip` option to check the request method seems to work well:

```
  var limiter = new RateLimit({
    skip: req => req.method === 'OPTIONS'
  });
```
