### ISSUE TITLE
Remove and ignore package-lock.json

### ISSUE THREAD

**Issue by DiegoRBaquero** [nfriedly/express-rate-limit#70]
The file is ignored when publishing to npm, it's useless to keep commiting, diffing, etc. It should be ignored.

**Comment by nfriedly** [comment]
Hi @DiegoRBaquero, I find it useful sometimes, so I'd like to keep it in the repo.  I'm just going to quote from the [NPM docs](https://docs.npmjs.com/files/package-lock.json) here, since they say it better than I can:

> **This file is intended to be committed into source repositories**, and serves various purposes:
> 
> * Describe a single representation of a dependency tree such that teammates, deployments, and continuous integration are guaranteed to install exactly the same dependencies.
> 
> * Provide a facility for users to "time-travel" to previous states of node_modules without having to commit the directory itself.
> 
> * To facilitate greater visibility of tree changes through readable source control diffs.
> 
> * And optimize the installation process by allowing npm to skip repeated metadata resolutions for previously-installed packages.

I agree with you that it makes diffing more annoying, but I think the benefits are worth it.

**Comment by DiegoRBaquero** [comment]
Hi Nathan,

Keep in mind that that it is not published in npm, so it’s useless for this package’s users. The tree installed its the one in the package.json ranges. It’s useful for developing, but rarely serves a purpose unless the dev team is large and has a large dependency tree.

Quoting: “One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package. “

I learned this a few days ago, just sharing the knowledge.
