### ISSUE TITLE
Feature request: Add skipSuccessfulRequests

### ISSUE THREAD

**Issue by DiegoRBaquero** [nfriedly/express-rate-limit#71]
Similar to skipFailedRequests, but skipping successful requests.

Would gladly do it, willing to accept a PR?

Would happily support this project as it will be used by @inalambria

**Comment by nfriedly** [comment]
Hi again @DiegoRBaquero,

Thanks, I suppose we could support that. 

Can you describe the use-case for it, though? Do you have something where failing requests are common and resource-intensive?

**Comment by DiegoRBaquero** [comment]
I'm building a URL shortener. I would like to only count failed requests, to prevent a scan on the shortened links.

**Comment by lukeaus** [comment]
Looks like this was done in https://github.com/nfriedly/express-rate-limit/pull/87 ?

**Comment by nfriedly** [comment]
Yes, thanks!
