### ISSUE TITLE
Why use this over nginx built-in rate limiting?

### ISSUE THREAD

**Issue by caderitter** [nfriedly/express-rate-limit#73]
Title - just a question. Would one be better than the other in any scenario, or are they generally equivalent?

**Comment by nfriedly** [comment]
I wrote this library for demos that we deployed to bluemix and wanted to make the source available and easy to deploy - so no dependencies outside of node.js. 

I haven't actually tested it, but my guess is that nginx is good ng to be better than this library in some respects, and that it would be a sound choice for rate-limiting, especially if you're going to be using it anyway.
