### ISSUE TITLE
Scaling out to a million users causes node to fall over

### ISSUE THREAD

**Issue by LouTheWise** [nfriedly/express-rate-limit#74]
A timed circular buffer might need to be created where the more entries in the cache the shorter time they are persisted. Another option is a computed hash that uses user time and server time. the same hash is sent to users between a timespan. ( x mins) The server can cache their results under the same hash using computed fingerprint based on their session. This would allow for a set of entries to be flushed at time rather than individual entries with a settimeout. Just a thought. Either way, the issue looks to be memory/resource related.

**Comment by nfriedly** [comment]
For something that's going to be serving a million users, you should probably use Redis or Memcached to handle the state; the MemoryStore is more appropriate for lighter-weight scenarios. 

As a band-aid, you could reduce the windowMs value (and then reduce the max hits as appropriate) to reduce the memory pressure. When I was at IBM Watson, I think we set it to10 minutes for most things. 

Also, if you have multiple servers but want to use the MemoryStore, make sure your load balancer uses sticky sessions to avoid having the IPs diplicated across all servers.

Also, the MemoryStore uses a single setInterval to flush all entries in the current window silmutaneously, no setTimeouts at all.

The delay option does use individual setTimeouts, but that only kicks in once the user has hit the limit, so it shouldn't be too resource intensive. If it is, just turn it off and start sending users an error once they hit the limit. (I plan to eventually move the delay code into its own module anyways...)

**Comment by nfriedly** [comment]
> Just a question, are you closing this because this is "by design" ?

Yea, kind of. I generally recommend checking out the competing modules for heaver-weight scenarios, but I think they're going to all tell you to use something like Redis for state.

Can I ask, what are you doing that's getting a million uniques but not generating enough revenue to pay for a Redis box?
