### ISSUE TITLE
'EINVAL: invalid argument, read' in first install

### ISSUE THREAD

**Issue by ardha2008** [nfriedly/express-rate-limit#75]
When installing i got this

```
PS F:\project> npm install --save express-rate-limit
npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN deprecated tough-cookie@2.2.1: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN project@1.0.0 No description
npm WARN project@1.0.0 No repository field.

npm ERR! code EINVAL
npm ERR! EINVAL: invalid argument, read

npm ERR! A complete log of this run can be found in:
```

What should i do ?

**Comment by nfriedly** [comment]
hum, I've never seen that one before. What version of node.js and npm are you on? (`node -v; npm -v`)

**Comment by ardha2008** [comment]
So do i, in other environment this running well
```
C:\Users\Ardha>node -v
v8.9.3
C:\Users\Ardha>npm -v
5.7.1
C:\Users\Ardha>
```

**Comment by nfriedly** [comment]
Hum, nothing out of the ordinary there. Run the npm install again with `-d` and then post the npm-debug.log file.

**Comment by ardha2008** [comment]
Fixed when running with ```-d```
Overall like this
``` npm install -d express-rate-limit ```

Thanks

**Comment by nfriedly** [comment]
That's strange (-d is just for debug logging). Oh well, glad it's working now :)
