### ISSUE TITLE
Permaban if limit gets hit multiple times?

### ISSUE THREAD

**Issue by switz** [nfriedly/express-rate-limit#77]
What's the best way to implement this? Thanks for the library!

**Comment by nfriedly** [comment]
You could supply a`onLimitReached` callback, and then keep a separate record of how many times that gets called for a given IP. Then write a second middleware that checks your separate record and permanently blocks anyone in it.

Note that `onLimitReached` is called for each request after the limit is reached, which is admittedly confusing, and will probably be changed eventually. However, the `req` object is augmented with ratelimit details including the total number of hits (and, this should be futureproof if it does change). So, you can do something like this:

```js
var RateLimit = require('express-rate-limit');

const ratelimitCounts = {};
const permabanLimit = 10;

app.use(function(req, res, next) {
  if (ratelimitCounts[req.ip] >= permabanLimit) {
    req.status(429).send("Sorry, your IP is permabanned");
  } else {
    next();
  }
});

var limiter = new RateLimit({
  onLimitReached: function(req, res, options) {
    if (req.ratelimit.count === req.ratelimit.max + 1) {
      ratelimitCounts[req.ip] = (ratelimitCounts[req.ip] || 0) + 1;
  }
});
app.use(limiter);
```

I haven't tested this, but that should give you the rough idea. Obviously this code has a few limitations, like loosing anytime the process restarts.
