### ISSUE TITLE
How to limit original client IP not proxy IP

### ISSUE THREAD

**Issue by bosna387** [nfriedly/express-rate-limit#79]
req.ip gets proxy ip instead of original clients IP 
I want to limit client IP not proxy IP.

Since clients IP is sent in req.params.ip field how would I limit on that value?

**Comment by impzero** [comment]
any news on this, dealing with the same issue

**Comment by nfriedly** [comment]
Sorry this got overlooked, this is solved by calling `app.enable('trust proxy');` - see https://expressjs.com/en/guide/behind-proxies.html
