### ISSUE TITLE
It's not work when windowMs setting to 0.001

### ISSUE THREAD

**Issue by 5idu** [nfriedly/express-rate-limit#82]
![1530604638908](https://user-images.githubusercontent.com/26264096/42206485-d187af82-7ed9-11e8-8045-ce1c5aa8c02a.jpg)

- How to limit API access in milliseconds, thanks !

**Comment by nfriedly** [comment]
The `windowMs` setting is already in miliseconds, so setting it to 1 is 0.001 seconds. Setting it to 0.001 ms would be 0.000001 seconds, which is too small of a window.
