### ISSUE TITLE
Rate limit at small windowMs

### ISSUE THREAD

**Issue by josephwong13** [nfriedly/express-rate-limit#83]
Hi, I am trying to prevent user from firing a POST API in a very short period of time, say 3000ms. This is my limit config:

```
const limiter = new RateLimit({
    windowMs: 3000,
    max: 1, 
    delayMs: 0 
});
```

And my route is something like:
`app.get('/test',limiter,(req,res)=>{res.end("hello")})`

When I test it by quickly firing the same API, I got the following result:
<img width="177" alt="screen shot 2018-07-12 at 4 54 09 pm" src="https://user-images.githubusercontent.com/15225843/42623075-8285b68c-85f4-11e8-8548-09234e5ae9fe.png">

The later API call did get block, but the previous one goes through despite the setting.

**Comment by nfriedly** [comment]
Are you using the cluster module, perhaps?

**Comment by jecsham** [comment]
Thats my code
`router
    .use('/osuapi/',limiter)
    .get('/osuapi', osuapi)`

Use `use `and `get`
My `windowMs` is `1000` and work perfectly.

**Comment by josephwong13** [comment]
@nfriedly Yes I am using the cluster module. I tried using Redis for storage and the limiter work perfectly now. Thanks!
