### ISSUE TITLE
IP Address Exceptions?

### ISSUE THREAD

**Issue by gdams** [nfriedly/express-rate-limit#84]
It would be really useful to be able to add a specific IP address or range of IP addresses that are exempt from the API limiting. Is this a feature that currently exists? If not how much work would it be to implement it?

**Comment by nfriedly** [comment]
Hi @gadams,

This can be done with the `skip` option - pass it a function like so:

```js
 var limiter = new RateLimit({ 
  // Other options...
  skip: function (req /*, res*/) {
     return req.ip === '1.2.3.4'; 
  }
});
```

(I'm writing this on my phone so that might not be perfect syntax, but it should give you the idea.)

**Comment by gdams** [comment]
thanks for your response!
