### ISSUE TITLE
Behind cloudflare

### ISSUE THREAD

**Issue by Jad3z** [nfriedly/express-rate-limit#85]
Hello,

My server runs behind a proxy ( Cloudflare ), what is the best option to use?

keyGenerator: function(req) {
  	return req.headers['cf-connecting-ip'] || req.ip;
}

or 

app.enable('trust proxy');

**Comment by nfriedly** [comment]
My gut feeling is that it will be safe to do both. 

But I've never actually worked with cloudflare that much, so I would recommend setting up a test with like a 3-hit limit just to see how it behaves and make sure it does what you're expecting.

**Comment by Jad3z** [comment]
I can confirm that my solution works for servers behind cloudflare.

**Marked Solved**

**Comment by nfriedly** [comment]
Awesome!
