### ISSUE TITLE
IP Address Issue

### ISSUE THREAD

**Issue by kalyantolety** [nfriedly/express-rate-limit#92]
I have reached the max limit when I hit 5 times to my API server and it has blocked my IP to my back end server. Now If I try to login using a different ISP which will have different public IP or even from a mobile internet, I get blocked even then and get same response. Is there any misconfiguration or which IP does it actually capture?

**Comment by nfriedly** [comment]
Where is your server hosted? Most likely you need to do `app.enable('trust proxy')`, however there are certain proxy setups that need additional configuration (I think cloudflare might be one).

**Comment by kalyantolety** [comment]
Its on AWS. I see by little digging that it is actually registering the application IP that is sending request. But if I hit the api with an application which consumes an API. It doesn't change at all and its filled up and blocking it. Which is not what I require. It should work with public IP if possible.

**Comment by kalyantolety** [comment]
I'm not under any proxy. Even I had it in the code. but didn't have any effect.

**Comment by kalyantolety** [comment]
I have done consoling req.ip. 
It gives me 127.0.0.1 on local, ::1 on postman, and returns the port that my application runs when consoled on server. Even when tried with different networks these values remain same.

**Comment by kalyantolety** [comment]
Can you guide me how can I use a custom IP address in keyGenerator func. 
Im currently using it this way..

app.enable('trust proxy'); // only if you're behind a reverse proxy (Heroku, Bluemix, AWS if you use an ELB, custom Nginx setup, etc)

var createAccountLimiter = new RateLimit({
  windowMs: 60000, // 1 hour window
  delayAfter: 3, // begin slowing down responses after the first request
  delayMs: 3*1000, // slow down subsequent responses by 3 seconds per request
  max: 5, // start blocking after 5 requests
  skipSuccessfulRequests: true, // doesn't count succesful requests
  message: "Too many requests created from this IP, please try again after an hour",
  keyGenerator: //
});

// only apply to requests that begin with below requests..
app.use('/ui/auth/', createAccountLimiter);
app.use('/ui/user/resetpassword', createAccountLimiter);

I have a way to send public ip from front end request. How can I put it inside keyGenerator ?

keyGenerator: function (req /*, res*/) {
            return req.publicIp;
        }

will this work?

**Comment by nfriedly** [comment]
If `req.publicIp;` is the correct IP, then yea, that should work. I was asking for the headers, because usually the correct IP ends up in some header, but there's only one or two that express checks automatically. If you see which header has the IP, than the keyGenerator can do `return req.headers['whatever-header-has-the-ip'];`

Oh, and the other thing I'll warn you about with your setup is the delay part got moved to https://www.npmjs.com/package/express-slow-down - so if you update express-rate-limit to v3, you'll want to add that also:

```js

var keyGenerator = function (req /*, res*/) {
  return req.publicIp; // of whateever
}

var createAccountLimiter = new RateLimit({
  windowMs: 60000, // 1 hour window
  max: 5, // start blocking after 5 requests
  skipSuccessfulRequests: true, // doesn't count successful requests
  message: "Too many requests created from this IP, please try again after an hour",
  keyGenerator: keyGenerator
});

var slowDown = require('express-slow-down');

var createAccountSpeedLimit = slowDown({
  windowMs: 60000, // 1 hour window
  delayAfter: 3, // begin slowing down responses after the first request
  delayMs: 3*1000, // slow down subsequent responses by 3 seconds per request
  skipSuccessfulRequests: true, // doesn't count successful requests
  keyGenerator: //
});

// only apply to requests that begin with below requests..
app.use('/ui/auth/', createAccountLimiter, createAccountSpeedLimit);
app.use('/ui/user/resetpassword', createAccountLimiter, createAccountSpeedLimit);
```

**Comment by kalyantolety** [comment]
Ya I got it working. But see my other issue when doing like that with IP's. And Thanks for the update.

**Comment by kalyantolety** [comment]
You put two functions createAccountLimiter and createAccountSpeedLimit in the parameters. Are they both needed or the updated one is enough?

**Comment by kalyantolety** [comment]
```
var keyGenerator = function (req /*, res*/) {
    if(req.body.publicIp){
  		return req.body.publicIp;
  	} else {
  		return "127.0.0.1";
  	} // or whatever we end up with
}
```

And I have this silly thing too. Because if I use any tools like postman, they wont get the public IP so in that case assigned default value when no value is present in my request.body

**Comment by nfriedly** [comment]
That works. You could also do something like `return req.body.publicIp || req.ip`, but whatever you're happy with.

>You put two functions createAccountLimiter and createAccountSpeedLimit in the parameters. Are they both needed or the updated one is enough?

If you update to express-rate-limit@3, then you'll need both. If you stay on 2.x then you don't need express-slow-down.

I'm just glad to hear it's working :)

**Comment by beez-dev** [comment]
why would we even put it in req.body? It's easily modifyable i believe, an authenticated user id in something like a token could be better I believe

**Comment by nfriedly** [comment]
Yeah, that's a good point. The IP should be something determined by the network stack, not part of the data sent from the client. But, some other form of authenticated user ID could go into the body or headers.

At any rate, this thread is about 6 years old. If you're having an issue today, you should probably start a new one.
