### ISSUE TITLE
Please add a these values as new parameters if possible

### ISSUE THREAD

**Issue by kalyantolety** [nfriedly/express-rate-limit#97]
1. If possible please add some thing that returns the no of attempts left. I want to use in a way like to display the no of attempts left. in the message text.

2. Need time remaining counter to display remaining time to reset after blcking.

**Comment by nfriedly** [comment]
For 1, check out `req.rateLimit.remaining` - it should be exactly what you want.

For 2, if you're using the memory store, check out `req.rateLimit.resetTime` - right now it's a unix timestamp, but I think I'm going to change it to a js `Date` object before documenting it.

You can see the code for these at https://github.com/nfriedly/express-rate-limit/blob/master/lib/express-rate-limit.js#L61

**Comment by nfriedly** [comment]
Ok, as of v3.1.0 and v2.14.0, `req.rateLimit.resetTime` is now a `Date` object when available, and is documented as such.

**Comment by kalyantolety** [comment]
Thanks. Please document this as well. It would be good..
